### ISSUE TITLE
Replace 'spec_helper' with 'rails_helper' in specs

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#1010]
We have ≈25 files that still have the old `require spec_helper` instead of `require rails_helper`.
That can cause problems, for instance when we try to run the 'supervisor specs' only:
 `rspec spec/controllers/supervisors` will throw an error. 

- [ ] Replace wherever applicable
- [ ] Run the specs (see Readme) to make sure everything is still working
- [ ] Doublecheck that we can now run the supervisor specs with `rspec spec/controllers/supervisors`

**Comment by carpodaster** [comment]
Not sure if the spec_helper instead of rails_helper was on purpose, ie. when unit-testing something without Rails (or other) dependencies. Running a single spec file w/o booting the Rails env is significantly faster. I may have been guilty of that one. With spring / bootsnap, application loading is less of an issue so might as well move everything to rails_helper to be consistent.
