### ISSUE TITLE
Suggestion / request: use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [rails-girls-summer-of-code/rgsoc-teams#1036]
First of all, thanks for Rails Girls Summer of Code!

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this repo? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/rgsoc-teams/pulls). I'll port the `rack` one across to this repo now.

I built Dependabot, but I'm honestly only suggesting it because I hope it can save you some time. Obviously having it run on open source projects helps boost its profile, and allows us to calculate better compatibility scores for updates, but if it's not useful to you it's really not worth anything.

If you decide to give it a try you can install it from [here](https://github.com/apps/dependabot) or [here](https://github.com/marketplace/dependabot). It's been through GitHub's security testing (to be allowed in the GitHub Marketplace) and is used by a few thousand organisations, and the source code is [here](https://github.com/dependabot/dependabot-core).

:octocat:

**Comment by klappradla** [comment]
Hey @greysteil 👋 

Thanx a ton for reaching out 💚 

I was actually using Gemnasium _(RIP)_ on the project before. It would email-alert me for security updated and I'd do them by hand.... I was then actually already looking at **Dependabot** as an alternative. But probably due to lazyness stayed with `bundle audit` for starters.

I'd personally totally be up for integrating it into the project - thanx for the reminder 🙏 

Let's have some more 👍 / 👎  here first though (@ramonh | @carpodaster | @F3PiX )

**Comment by carpodaster** [comment]
¡Hola @greysteil!  Thanks for suggesting Dependabot. I think it would be great to have an automatic dep check system in place again. I'm all 👍  for trying it out. 😄

**Comment by alicetragedy** [comment]
+1! I'd also love to consider this for our other repo `summer-of-code` because I've been doing these security updates manually as well 😅

**Comment by carpodaster** [comment]
@alicetragedy you got it :)

**Comment by carpodaster** [comment]
@greysteil I've added Dependabot to our repo! Thanks again for suggesting it 💯 🎊
