### ISSUE TITLE
Add location selection on mailings

### ISSUE THREAD

**Issue by bastilian** [rails-girls-summer-of-code/rgsoc-teams#110]

**Comment by carpodaster** [comment]
@anikalindtner (or anyone else): Do you remember what this was about? If yes, could you sketch the feature here so that we might work on this as part of the SoC? Merci! :smile:

**Comment by anikalindtner** [comment]
@carpodaster I think it was a feature, so that we could email people in specific locations. Say, if we have a party in Vienna, let all the viennese people know via email and don't bother the onces living in L.A.

The feature should be available to organizers writing an email in /mailings. So that next to choosing who to address (students/ teams/ coaches), you can also choose a location filter for that.

**Comment by carpodaster** [comment]
@anikalindtner I don't think we can cluster by location as our users' locations will be very diverse. Maybe selecting students/teams with a checkbox individually would solve the problem?

**Comment by carpodaster** [comment]
I'm closing this. It's unclear how "by location" would be implemented. Feel free to re-open!
