### ISSUE TITLE
Fix weird check box

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#133]
I have no idea what this check box does? Does anyone know?

![screen shot 2015-02-19 at 19 16 45](https://cloud.githubusercontent.com/assets/1711357/6272982/146f2f38-b86c-11e4-9f39-6e256e5b37d9.png)

**Comment by anikalindtner** [comment]
WEIRD CHECKBOX BEING WEIRD

![](http://1.bp.blogspot.com/-Y1qwLqBttb0/UGRZoAYh97I/AAAAAAAACMs/tovFf31xLWA/s1600/Light+Switch+2.jpg)

**Comment by alicetragedy** [comment]
haven't looked at the code yet, but from the text below it, it looks like it might be something to show/hide the email address..?

**Comment by anikalindtner** [comment]
yeah.. i also think so. but it's neither near the email field, nor does it say so ;D

**Comment by alicetragedy** [comment]
okay, found it - it's exactly what we thought it would be ;)

**Comment by alicetragedy** [comment]
Sooo I took a quick look at it (it's actually driving me crazy now) and I don't know where the problem is. or, actually I do: seems like `inline_label` is not recognised anymore for whatever reason. I'm not sure if it's a nested_form problem, because I had a rails 4.0.5 project with simple_form 3.0.2 and `inline_label` worked there with no problem, and `inline_label` doesn't seem to have changed much in simple_form 3.1.0rc1. I'm clueless :sob:  
The quick fix for now would be to add a "normal" label so that it looks like this, but it's quite ugly. (at least the text shows, though).

![screen shot 2015-02-19 at 20 51 23](https://cloud.githubusercontent.com/assets/3143348/6274631/1fe189bc-b879-11e4-86f7-a35e2bb1b29f.png)

or maybe @carpodaster or @lislis have more of a clue?!

**Comment by carpodaster** [comment]
Bootstrap and simple_form seem to be at each others' throats. This is one of the many facets of #126 :sob:

**Comment by alicetragedy** [comment]
yeah, it's pretty terrifying.
should I add those changes above though @carpodaster so we at least don't have floating checkboxes? ;)

**Comment by carpodaster** [comment]
I'm sorry @alicetragedy I only skimmed your comment :blush: Yes sure, go fo' it!
