### ISSUE TITLE
Nice-to-have: team logo (on team details page)  for the activity stream 

### ISSUE THREAD

**Issue by ellenkoenig** [rails-girls-summer-of-code/rgsoc-teams#17]
alternatively, either the gravatar images of  the team members could be used in combination or the project logo

**Comment by carpodaster** [comment]
@roosdebildt do you want to work on this?

Gravatar is probably not a good option since I doubt all teams have a separate email address set up. Maybe grabbing the individual gravatar images of the students and fusing them together client-side with CSS/JS voodoo?

That would remove the requirement to fiddle with file uploads right now.

wdyt?

**Comment by roosdebildt** [comment]
we'll have a look at it as soon as we're ready! sounds like a great first commit for @F3PiX and me :)

**Comment by roosdebildt** [comment]
I think I'm first going to try putting both of the individual github avatars of the students next to each other, so no fuzz for the user. In case we want to upgrade this with upload-/fusing-goodies client-side, we can do that later! waddoyousay?

**Comment by carpodaster** [comment]
Sounds perfect! :+1: :smile:
