### ISSUE TITLE
Discuss: add "join team" button?

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#187]
Right now a user (eg. coaches, mentors) can never _join_ a team. You can either create a team or _invite_ people to an existing team that you're a member of.

Should we add a button that basically knocks on the door and ask the team members to be let in?

Who shall be asked? Aall of them? Just the students? The one who created the team (which we don't track yet)?

**Comment by alicetragedy** [comment]
I think this is a tricky question. On one hand, I don't think the students should rely on members adding themselves to the team/I think it should be their responsibility.. on the other hand, however, I know that some of the project mentors were slightly 'frustrated' about having to wait to be added. So I think having the possibility to join a team would be :+1: 

As for the second part of the question, I think that the least people need to be asked, the better for the workflow.. If we pick the last option (the one who created the team), which I would tend to go with, this poses the problem: what happens when the owner of the team is not on the team anymore? (for whatever reason, ie. a student dropping out). 

Maybe we need to think about the goals and priorities of the teams app, and go from there.

**Comment by sareg0** [comment]
I'm really happy to see this as a potential task for the team during the summer, however, as I think it will be a great flow improvement. We could also focus group on this at some point if needed :)

**Comment by F3PiX** [comment]
I like the way LInkedIn offers pre-approval on invites. 
Students could pre-assign coaches before they ask the coach to join, pre-assigned coaches could add themselves to the team without waiting.

**Comment by carpodaster** [comment]
Students will invite coaches. You can't join the other way round. Closing.
