### ISSUE TITLE
Make email required field

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#227]
email looks like a required field, but we still have users that don't have an email 

![screen shot 2015-06-08 at 12 10 27](https://cloud.githubusercontent.com/assets/1711357/8035073/d01ee5f8-0ded-11e5-890b-7fd03254baae.png)

**Comment by carpodaster** [comment]
Hey @anikalindtner - this is because a user can be created by adding a GH handle to a team. The app tries to get the email from GH but if that fails for some reason (e.g. misspelled GH handle, no email address available, network error), the user record on the teams app will be left without an email. There is little to nothing we can do about it.

**Comment by anikalindtner** [comment]
ah okay... but then we have to think about that. because maybe this shouldn't be allowed then? hmmmm have to think about that. since we do need the email addresses desperately for contacting them.. hmmmmm

**Comment by carpodaster** [comment]
@anikalindtner An  email is required as soon as one tries to edit the user record, just not when it is created from a Github handle. I have no idea how to do it otherwise (but then again, I'm sleep-deprived :smile: )
