### ISSUE TITLE
Email address in student profile should be visible to supervisor

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#236]
At the moment, it seems the email address of students in their profile (https://teams.railsgirlssummerofcode.org/users/user-id) is only visible to orgas – meaning the supervisor of the team can in no way check whether the student has added their email address.

**Comment by sareg0** [comment]
After a discussion with @anikalindtner it has been determined that, yes, the supervisors should be able to see the student email addresses.

I have create a pull request for review to try and fix this.

This would allow all supervisors to see all user's email contact.

This is how I did it because some supervisors will be filling in for others during the summer, so I felt this is ok. 

Please let me know if it isn't.

pull request #240

@carpodaster and @alicetragedy perhaps you could review it.
