### ISSUE TITLE
Add link to Github source

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#241]
We should make it easier for people to contribute to the teams app. What about a [Github ribbon](https://github.com/blog/273-github-ribbons) on the front page? Or just a link to the repo in the footer?

**Comment by alicetragedy** [comment]
JA! I vote ribbon :ribbon:

**Comment by carpodaster** [comment]
@F3PiX & @roosdebildt, this could also be a great warm-up

**Comment by roosdebildt** [comment]
do we want the ribbon only on the front-page (=activity page) or appearing on all pages...?

**Comment by carpodaster** [comment]
If it's not too obtrusive, I'd vote for every page

**Comment by roosdebildt** [comment]
Could we also use one of these: 
https://dribbble.com/shots/245356-Fork-me-on-GitHub

They're free of use and look way nicer + fit better with the size of the header:

<img width="1242" alt="screen shot 2015-07-15 at 12 45 12" src="https://cloud.githubusercontent.com/assets/11146524/8696760/6e3b8656-2aef-11e5-8d53-f6d5f87be604.png">

**Comment by alicetragedy** [comment]
I like those too!
Do you think it would be possible to make a greyish one? It doesn't say anything on the dribbble, license-wise, about modifying the existing ribbons. Not sure which color would fit best otherwise, given our bright red header :)

**Comment by roosdebildt** [comment]
I could make a gray-ish one for sure! But I just found out the quality is superlow :( I e-mailed the guy but I'm looking for other solutions/images, too.

**Comment by alicetragedy** [comment]
@roosdebildt we have a designer who joined our team and helped me design the stickers (I made the first edition, she made all the rest). Maybe we could ask her to design a ribbon for us :)
I also just found this generator: https://codepo8.github.io/css-fork-on-github-ribbon/
Might be interesting to give it a whirl.

**Comment by carpodaster** [comment]
I love the CSS-only one!

**Comment by roosdebildt** [comment]
Since I think this still looks a bit awkward with the header:

<img width="1242" alt="github-ribbon" src="https://cloud.githubusercontent.com/assets/11146524/8706784/e272114c-2b31-11e5-9e4f-b589f3001153.png">

I'm going to try to design my own ribbon as an evening side project :) Based on a vertical one:

![ribbon-vertical](https://cloud.githubusercontent.com/assets/11146524/8706815/1b66c132-2b32-11e5-8be9-ca28a4fb8b07.png)

But tell me if you prefer the original GitHub ribbon, 'cause that would be a lot of effort for nothing ;)

**Comment by roosdebildt** [comment]
sidenote @alicetragedy: shall I add you to our fork so we can keep the original workflow of PR's with our fork before merging with upstream?

**Comment by alicetragedy** [comment]
@roosdebildt I actually have no major opinion on this – I thought maybe the css generator would save you a lot of (design) work. I agree that the vertical ribbon in the example looks a bit big, I'd make it maybe two-thirds of its current size, but I'm sure you can play around with it and see what works best. 
I'd love to be added to your fork so I can keep track, if you want. Or feel free to ping me if you want my opinion on anything especially if css-related, due to @carpodaster's allergy to it ;)

**Comment by sareg0** [comment]
also I feel like the diagonal 'fork me on github' ribbon is sort of more known, and looks less like a bookmark on kindle ;)

**Comment by carpodaster** [comment]
Done in #292
