### ISSUE TITLE
Feature Request: Make jobs board accessible to all seasons

### ISSUE THREAD

**Issue by sareg0** [rails-girls-summer-of-code/rgsoc-teams#247]
This is something that I discussed recently with previous grads, both searching for OR with jobs to offer from their own contacts.

The user story goes like this;

"I as an alumni want to see all jobs for jr devs that are being collected, and also know where to send said job offers if I receive them"

Our process currently works like this. 

1. we get word of a job offer from sponsors/supporters of RGSoC, and make sure it is worth putting up/a decent offer. We generally only allow sponsor to put up jobs, but will make an exception for really high quality employers/ones we can vouch for. 
2. We input the job offer manually into the 'Jobs' section of the teams app
3. We prepare a digest of job offers in Mailchimp, and send to alumni.
(sometimes step 2 gets missed)

Being able to have a jobs board that is not limited to the batch year, and that all Alumni from all years can see would be ideal. Currently the Alumna goes to the teams app under their batch year, and can see jobs there.

Being able to filter jobs by when they were published would also be good, to make sure that alumni do not apply for a job offer that is super out of date.

The next step would be being able to send a digest email of all new job offers. That is a nice to have.

**Comment by carpodaster** [comment]
This sounds like a good improvement to the exisiting job board but I would like to see more +1's, indicating that it's a feature we really want to have.

Personally, I am not quite convinced, mostly because "sometimes step 2 gets missed". I don't recall the job board being filled with enough job positions to justify working on that section. It's just not visible enough and in fact I've already been thinking of removing the jobs section altogether to counter possible feature-bloat.

/discuss! ;)

**Comment by sareg0** [comment]
yes, I think that the jobs board could potentially be separate to the teams app altogether.

I am gonna ping @berlintam who had some great input on this topic of the jobs board.

**Comment by F3PiX** [comment]
I feel for both sides. I agree that SoC-site may not the best place for listing job offers. On the other hand, this could be the place to list job offers for the not-too-experienced Nuby's. 
Then again, do company's really need such a place?

**Comment by berlintam** [comment]
I think that having a job board as part of rgsoc is awesome. I know that after I finished rgsoc I was frantically looking for a job and didn't know where to go, and I looked to rgsoc for support in this b/c they had held my hand throughout the whole summer. In my opinion it makes sense for rgsoc to offer this b/c it's like they're helping students cross the finish line in finding a job. you know what I mean? However given this is called 'the teams app', somehow having a job board in here doesn't make much sense now that I think about it, since it doesn't really have anything to do with managing the teams. 

I also love the idea of getting an email, like once a month, about new job offers. But this is only really worth it if there are enough in there. 

I think it would ALSO be awesome if there was a RG Job board somewhere out there....  one that is a flushed out version of this: https://github.com/Malwine/juniors-in-berlin (but for the whole world)

**Comment by carpodaster** [comment]
In today's weekly hangout we decided to remove the job board from the teams app. We agreed to forward job offers to our mailinglist(s) (needs checking w/ sponsor perks). We can also direct alumnis to the juniors-in-berlin list at the end of the summer as an inspiration to create similar lists for other regions.

**Comment by F3PiX** [comment]
Would you mind to leave the job_offers in the code_base for a week or so? It might proof to be a handy transition sandbox for us.

**Comment by alicetragedy** [comment]
@F3PiX I don't think we will remove it super soon, so worry not – but thanks for letting us know. :)

**Comment by F3PiX** [comment]
:+1:
