### ISSUE TITLE
Checked-up-on-them doesn't work for Team Techylite

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#251]
When hitting the "checked up on them" button (either with or without comments) on this team, nothing happens: https://teams.railsgirlssummerofcode.org/teams/28

Ideas? @carpodaster @sareg0 @alicetragedy

**Comment by alicetragedy** [comment]
I will take a look later today – first guess is that something in that team somehow is set to nil somewhere(?), keeping the comment from being saved. We'll figure it out!

**Comment by alicetragedy** [comment]
okay, so I knew this was going to come back to bite us in the ass... 
Apparently the problem is something we've had problems with before: that the mentor of the team is a mentor that is also a student, so somehow the Comment doesn't save and gives some weird gibberish error message I couldn't really understand :D and I don't know how to fix it. I tried fixing it locally by removing Maren as a mentor from team Techylite (#yolo), and now commenting works for me (locally at least). 
@carpodaster do you have any idea about this, and what we could do as a workaround?

**Comment by carpodaster** [comment]
@alicetragedy It would seem we can only solve this by removing the student-must-only-be-student constraint. I would against it, though, and indeed remove Maren as their mentor on production.

**Comment by alicetragedy** [comment]
@carpodaster yeah, it's a little tricky.. I'm just wondering though why, if this is a problem, we've accepted Maren as a student if a student is not supposed to have any other role? :p 
I thought maybe we could remove the constraint for this year as well will probably not be adding any more students / roles. But I'm okay with removing her from production, I'll get in touch with her and see if that's okay?

**Comment by carpodaster** [comment]
@alicetragedy the constraint is in place so that a student cannot join another team as a student (and thus cannot apply with more than one team). Not allowing them in a different role is probably an undesired side-effect, but I have to say that I have little motivation to program around this one edge-case. 

Removing the constraint would mean we risk re-introducting it next year again. There are no implications removing her from the teams roster as mentor now that the application phase is closed (at least I can't think of any, since mentors have no super-powers on the teams app).

So yes, :+1 for talking to Maren :smile:

**Comment by alicetragedy** [comment]
@carpodaster that makes sense! we'll have to try and keep that in mind for next year, so we don't have the same weird mess. I'll remove her as soon as I've talked to her :)

**Comment by alicetragedy** [comment]
@carpodaster I just realised that removing her will also mean she will not receive the mentor emails/important communication. is that an ok side-effect we want to have? UGH so complicated..

**Comment by carpodaster** [comment]
Ah, you're right. IIRC she's not the only mentor, right? Would it be enough to rely on the second mentor to relay these info mailings?

**Comment by alicetragedy** [comment]
@carpodaster Erik is the second mentor, which is a bit strange – not sure how much he actually reads the mailings, but I could give him a heads up in any case to forward the email to her.. or we do so ourselves (just have to remember it every time).

**Comment by anikalindtner** [comment]
I think that' still a mistake that Erik is in there.

**Comment by alicetragedy** [comment]
@anikalindtner @carpodaster I'll replace Erik with Anja and remove Maren. #yolo

**Comment by carpodaster** [comment]
Could be they applied for a second project where Erik was the mentor. In that case, we need Maren as a mentor, but can we ask her to create a second GH account?

**Comment by carpodaster** [comment]
> @anikalindtner @carpodaster I'll replace Erik with Anja and remove Maren. #yolo

Oder so! :smile:

**Comment by alicetragedy** [comment]
Fixed!
