### ISSUE TITLE
Refactoring: Make Comment polymorphic

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#346]
The Comment model has grown a set of commentable records' foreign keys. We should refactor it into a `belongs_to :commentable, polymorphic: true` instead of listing all types of recods individually.

There's no deadline for this and can be done whenever there's time. @marcgreenstock and @lucaspinto, is this something you could see yourself working on?

**Comment by rishiip** [comment]
Steps for make `Comment` model polymorphic:

- Create Migration for make appropriate changes in `comments` table
- Perform modifications within `Comment` model
- Perform modifications within `Team`, 'User', `Application` and `Project` models
- Test the changes and generate PR

@carpodaster : It would be great if you can verify above steps and suggest changes if you find any so that I can start working on it. :blush:

**Comment by carpodaster** [comment]
Hello @rishiip, sorry for the slow response. It's great that you want to work on this, thank you! The steps you describe are :ok_hand:  :smile:

**Comment by rishiip** [comment]
@carpodaster : No worries. :blush: I'll start work on it and generate PR on the same.

**Comment by rishiip** [comment]
@carpodaster : It would be great if you can suggest me which main forms/screens I need to verify/check while test the things!

**Comment by carpodaster** [comment]
@rishiip I have checked the codebase only briefly, so this list might not be complete:

* app/views/projects/show.html.slim
* app/views/rating/applications/show.html.slim
* app/views/rating/todos/applications/show.html.slim
* app/views/supervisor/dashboard/index.html.slim

**Comment by carpodaster** [comment]
I've started working on this now (because I desperately want to [comment on status updates](https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/263)), but I'm struggling with the best way to migrate existing data – mainly because we recently had the issue that older migrations didn't apply anymore. I'm hesitant about adding data transformation loops referencing actual Rails models (which may no longer exists in one or two years).

@alicetragedy @klappradla @michaelem @ramonh  do you have any advice / ideas / good experiences to share?

**Comment by michaelem** [comment]
What I usually do in that case is just define the minimal required model class inside the migration. That way you can still use ActiveRecord in the migration without running the risk of the class not being there at some point down the line.
It also does not add a lot of complexity since usually its just an empty Subclass of ActiveRecord::Base with maybe one belongs_to statement (whatever you need to do the migration).
Does that make sense in our case?

**Comment by klappradla** [comment]
Yes, @michaelem's approach is a classic here *(see for instance [this blog post](http://railsguides.net/change-data-in-migrations-like-a-boss/) on how it can look like)*. A shorter alternative is to just wrap the data transformation part in a `begin`- `rescue` block - does the job as well.

A wholly different solution: use temporary rake tasks *(see for instance [this blog post](https://robots.thoughtbot.com/data-migrations-in-rails))*. I personally don't really like this approach, because it leaves two questions open: 1) who when removes the task again? 2) is the task run in every context where I intended it to?

**Comment by carpodaster** [comment]
@klappradla @michaelem ¡muchas gracias! Those are very valuable suggestions, and the blog post looks very intriguing!

I've always gone for the temp. rake task approach in my projects (a `:single_run` namespace). It's brittle when someone didn't get the memo run task X after migration Y, but the impact isn't big since everyone is working with anonymiized dev dumps anyway; no one really migrates from 4.years.ago to present.
