### ISSUE TITLE
Application process: categorize / bundle application form fields for the individual steps

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#367]
* [x] Find descriptive "category" names (e.g. "Personal Info", "Programming Background")
* [x] Define which  form fields should go into which step

**Comment by alicetragedy** [comment]
For the tab categories there are three possibilities: 
1) Student 1, Student 2, Team (includes project info), Coaches 
2) Student 1, Student 2, Team (including coaches) and Project
3) Student 1, Student 2, Team, Coaches, Project 

Nr. 2 seems more intuitive, but I don't know what your thoughts are on the topic. 
Nr. 3 feels like an overwhelming amount of tabs to me, and I'd like to stick to 4 tabs max, if possible.

**Comment by alicetragedy** [comment]
Categories:

- Requirements
- Personal Information
- Financial Information (could go into personal?)
- Programming skills
- Teamwork
- Goals & Motivations


Step 0: Requirements (read and understood application guide, identifying as a woman/non-binary, team member location is the same)
Step 1: Personal information (includes basics like name, location, and background information text. if needed also financial information dropdown)
Step 2: Programming skills (checklist and big text area "how did you get into programming")
Step 3: Teamwork (since this is a self-guided program, how do you envision working together & how/why did you choose this project/issues)
Step 4: Goals & Motivations (what is your goal for the summer, + motivation essay)

Did I forget anything @carpodaster?

**Comment by alicetragedy** [comment]
I believe that as soon as https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/390 is merged we can close this.
