### ISSUE TITLE
Increase session timeout for Github logins

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#372]
When we were working on the Supervisor Dashboard during SoC2015, some of the supervisors told us about annoyances with Github Authentication:
1 having to authenticate w GitHub "all the time" (which boiled down to: every day or every few days)
2 after auth w GitHub, you are not returning to the page where you came from

#1 Not sure if this managed by GitHub. If not, it can be managed by Devise (AFAIK): is it okay to extend the time-out (the user session without activity) to 1 or 2 days?

#2 We should redirect back to previous page.

**Comment by alicetragedy** [comment]
I think Nr. 2 is definitely a huge priority. Thanks for adding this! 👍

**Comment by anikalindtner** [comment]
AFIAK @carpodaster said that we can't do anything about the redirect to the previous page since that's handled by the GH auth thing? I also find this super annoying and would love to have this different.

**Comment by carpodaster** [comment]
Ohai. I have may have just fixed no. 2 :relaxed: 

If no. 1 was reported as being annoying during the summer we should definitely fix it. It would be super-nice if you could work on that, Maud. Especially because I have no idea about devise's internals :grin:

**Comment by alicetragedy** [comment]
Carsten's :sparkles: magical dev powers :sparkles: 

![tumblr_m9dlcwp2yr1qiyseco3_250](https://cloud.githubusercontent.com/assets/3143348/12989968/085e07d6-d108-11e5-8b14-13e311861614.gif)

**Comment by anikalindtner** [comment]
WHOAA

**Comment by F3PiX** [comment]
:bow:

**Comment by beanieboi** [comment]
@F3PiX let me know if #373 fixed the issue, hopefully we can close this then :)

**Comment by F3PiX** [comment]
Hi @beanieboi, I don't know how to check if it is fixed. I never had this issue myself. It _sounds_ like it is solved though ;-)

**Comment by alicetragedy** [comment]
@carpodaster seems like the "redirect after login" issue is still not fixed — at least it seems like it doesn't work with the https://teams.railsgirlssummerofcode.org/apply link, which is a bummer because I would love to link to the application page directly from ie. the application guide. Right now, the "blogs" as an index page for the teams app (which is the page we link to by default, and the page which is shown by default when logging in) seem to be pretty confusing for most students applying. I'll investigate further, to see if there's anything we've overlooked..

**Comment by alicetragedy** [comment]
I think we can close this!!!! :tada: :confetti_ball: :raised_hands:
