### ISSUE TITLE
Feature request: SEARCH! 

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#379]
The community area (/users) tends to become quite full every year. Even though we have pagination in place, finding someone in there is not 100% user friendly. I'd love for us to have a search in there in order to find someone quickly (mostly by name/username).

**Comment by carpodaster** [comment]
Morning @alicetragedy! Agreed, a search would be very helpful. I'm not too sure about searching for a (user)name, though. Ideally, you'd search for people in your vicinity, but that requires geocoding all users based on their location and may yield funny results if someone could not be geocoded (e.g. because they decided not to give any location info).

**Comment by F3PiX** [comment]
I thought that I was able to do that, so I tried and I COULD :tada: 
@carpodaster: I know it is not the BEST reason to add a feature :-) . WDYT?
See PR #382

**Comment by alicetragedy** [comment]
thanks @F3PiX! :sparkles: 
@carpodaster you're right, for a lot of users, searching by location would make a lot of sense. In my case though, I often look up if people already exist in our community list and do so by name. Anyhow, I'm leaving this open, as I think we might want to think about ways to improve the search that Maud has already added (ie. adding location).

**Comment by F3PiX** [comment]
In that case: maybe searching team names is also a nice future improvement.

**Comment by F3PiX** [comment]
Good one, I will add that. And very glad that you will take care of the styling 🍹

**Comment by F3PiX** [comment]
I need some help, please. 
First option is a reset link, that is disabled until a search is committed. This works, but needs tender love and caring in the css. 
![active link](https://cloud.githubusercontent.com/assets/6314687/16994596/51628f42-4ea8-11e6-8f02-83696e3727f7.png)
![inactive link](https://cloud.githubusercontent.com/assets/6314687/16994607/5f0fe96e-4ea8-11e6-8c3c-8d266ce72ff5.png)

Second try was with .js script on the link, to hide the link, and show after GO is clicked. The script works, but the link immediately disappears when the page is refreshing. Which makes sense, because after refreshing the hidden setting is activated.
Third try was similar script on the GO button. Same effect.
This is my first js script ever, so please don't think I know what I am talking about ;-) 
 
What to do? Quick fix is PR with option 1 (screenshots). 
Or I put the JS script in the PR, and someone takes over?

**Comment by katrin-k** [comment]
I'd say the first option is fine so far. 
I can take over CSS for the link. 

My JS is also not good enough yet to take over option 2. I had a similar problem on a previous website and from what I learned when talking about it with a colleague was that loading the table with AJAX would be the solution. (We didn't implement it back then, so sadly I'm still missing the knowledge. Ajax is on my learning plate for August, though…) 
Is there's sth. in RoR that can do that?

**Comment by F3PiX** [comment]
That is great! And yes, if we could have an ajax wizzard to make the page only reload the table and not the whole page, I am sure it will work. I'll move the simple link to a PR. See you there!

**Comment by F3PiX** [comment]
The reset button is added in #379.
Still open: the search for team names (and maybe other search criteria).

**Comment by F3PiX** [comment]
Search for team names is added in #509.
