### ISSUE TITLE
Navigation bar on teams.railsgirlssummerofcode.org

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#380]
It seems to me that certain links are missing on the navigation bar:
1. Link to the 'Projects' page https://teams.railsgirlssummerofcode.org/projects
2. Link to the 'Activities' page https://teams.railsgirlssummerofcode.org/ (yes, you can get there by clicking on the logo, but this is not super transparent)

I think that the navigation bar should somehow reflect the structure of the website.

**Comment by carpodaster** [comment]
Hello @mkalininait - thanks a lot for the suggestion. Yes, the navigation bar needs some love! The problem is that we have too many potential menu items and too little space.

There are some menu items that pop up during different phases of the RGSoC season (like project proposal phase,  application phase, actual coding phase, post summer …), too, which makes it even more difficult to "plan" what actually fits on the one line nav bar.

Ideally we'd have a dropdown lists. PRs for an updated nav bar concept are totally welcome! :)

**Comment by F3PiX** [comment]
@alicetragedy and I briefly discussed the possibility of changing the header into a 'real' bootstrap navbar. I suppose that would be the first step. Wdyt @alicetragedy ?

**Comment by alicetragedy** [comment]
@F3PiX I think the teams app might need some restructuring anyway, and the navbar should reflect that :) as Carsten pointed out it's difficult when the menu items change throughout the summer according to the different phases, however I think we could definitely change it into a 'real' bootstrap navbar. :+1:

**Comment by izuroxx** [comment]
Hi! I'm a newbie here but this issue seems very interesting. Is it possible for you to precise if it should be done by 1) adding two links to existing solution (as stated in original task description) 2) adding some drop down list (as suggest @carpodaster) 3) changing menu into bootstrap navbar (as suggest @alicetragedy) or you want to decide on this this during the summer of RGSoC (possibly changing/adding more tasks to Nav Bar Revamp milestone)? Thank you!

**Comment by alicetragedy** [comment]
Hi @izuroxx,

We have not quite discussed it/made a decision yet, but I believe we will not just be adding those two links (as pointed out after that, some of the links are dependent on the program phase) so we will probably change the menu to a bootstrap navbar, and add dropdowns there where deemed necessary, with some of the single menu points inside the dropdown will appear/be hidden depending on the phase the program is in. I hope that's a thorough answer! 

Depending on how annoying it is, it might even be fixed before the summer starts, but I would not necessarily count on it ;)

**Comment by izuroxx** [comment]
Thank You @alicetragedy!

I have a few questions regarding other issues, but i guess i'll put them in one email and send it to you (if that's ok) - i see all of you have a lot of work, hope i'm not bothering you too much :)

**Comment by alicetragedy** [comment]
@izuroxx absolutely, go ahead and do that. :+1:

**Comment by anasofiapinho** [comment]
Just noting that students asked me for the links to their projects but they couldn't find them because there was no link to "Projects".

**Comment by carpodaster** [comment]
@anasofiapinho we only display the link to `/projects` during the application period. It can be still be accessed as https://teams.railsgirlssummerofcode.org/projects

**Comment by ramonh** [comment]
As discussed, I'll start taking a stab at this 😄

**Comment by carpodaster** [comment]
Thank you @ramonh !

In an attempt to summarize what we've just talked about in the call:

* Needs links to dashboards (including the selection sub-app for reviewer-roles)
* Most of season-phase-specific conditionals  are in place to keep the single-line nav bar short. Some may be worth keeping (in order to remove cognitive load), others could be displayed all-year
* We need some kind of secondary nav level but how to group the existing elements?

**Comment by ramonh** [comment]
Thank you for the summary @carpodaster!

**Comment by klappradla** [comment]
Hey @ramonh, I'm taking a look at these things. I need to add a navigation item for things related to #581 - so I'll see if I can clean up the navbar to actually make this possible :v:

Fine?

**Comment by ramonh** [comment]
That's totally cool, thank you @klappradla ! :bowing_woman:

**Comment by klappradla** [comment]
Just to make sure: non signed in users can look at both, `teams` and `conferences`?

**Comment by alicetragedy** [comment]
@klappradla sorry, completely overlooked your comment. Yes, non signed in users can look at both `teams` and `conferences`. 👍 
can't wait to see the new pretty nav bar 🎉 🎊 🎈 :party_parrot:
