### ISSUE TITLE
Add these markdown docs to the help section

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#410]
I wrote an application how-to, but I can't get the app run locally, so I need some help by someone who can add this content to the help section:

+ https://gist.github.com/anikalindtner/759af72999f2c9a2e46f
+ https://gist.github.com/anikalindtner/eb66868711c6d4183e05#file-fill-out-your-application-md

Who can take this on? :sparkling_heart:

**Comment by anikalindtner** [comment]
When this is done we should add "The how-to-apply guide you'll find in our [help](https://teams.railsgirlssummerofcode.org/pages/help) section." After "Please read our Student Application Guide"

![screen shot 2016-03-13 at 22 28 02](https://cloud.githubusercontent.com/assets/1711357/13731506/e9c493be-e96a-11e5-9cc5-ae1c3316e9d1.png)

**Comment by alicetragedy** [comment]
this is AWESOME!!!! thanks! <3 
(we might have to change a couple of screenshots in the future if we add a fifth tab, so I might ping you about this again)

**Comment by anikalindtner** [comment]
sure! ping away! :)

**Comment by alicetragedy** [comment]
If no one grabs this task by tomorrow, please ping me about it — happy to deal with it then. :)

**Comment by carpodaster** [comment]
> we might have to change a couple of screenshots in the future if we add a fifth tab, so I might ping you about this again

I'm thinking: is it better to have this on the public website instead of the Teams App? The teams app is not exactly the please where we think about updating copy. E.g. the help section lay there orphaned for quite a while and I fear that will happen again.

**Comment by alicetragedy** [comment]
@carpodaster yes and no. Since this is quite specific to the teams app, I feel like info that is relevant to the use of the teams app (how to log in, how to look for a partner using our app, how to fill out the application form properly, how to edit your profile) should be in there somewhere. You're right in pointing out that we hardly ever update copy on the teams app — maybe this is something we (not wanting to force anyone into this, so maybe I should just say I) should focus on a bit more. We've actually had this conversation before, about where information that is specific to students (and not just possible applicants) should go. 
Another difficulty I have with adding this info to the website: people are already confused as it is when coming to the website to look for information, and I feel like adding this sort of extra information might confuse them even more. I'm happy to have a discussion about this and see pros and cons of both approaches :)
This is kind of a "structural" question I guess (and might help with how we want to structure the navigation in the teams app as well): do we want to separate areas in the teams app by role? ie. if you're an applicant / student, these are the sections that might be relevant to you. I think if the overview was a little better (not wanting to criticise anything about the teams app currently, but we all know how it's grown into a "monster"), it would be easier to remember to make such updates.

**Comment by carpodaster** [comment]
@alicetragedy Those were convincing arguments – let's keep it on the teams app! I really only fear for outdated (and thus: outright _wrong_ ) information since I know I for one don't have static website copy on my mind when I'm working on the teams app; the code just changes so much faster than I think we can keep up with on-page help :cry:

**Comment by alicetragedy** [comment]
@carpodaster yes, I know. it's very frustrating, for devs and orgas as well as students 😖For example, the help page said that you could change team github and twitter info on your edit profile page, but as it turns out, this cannot be done until you are a selected team. Small issues like this do slow us down, so maybe this is a good point for why we might want to try to have better documentation for the teams app. I'd love to hear your input on this! And yes, I know that for many people tests = documentation ;)

**Comment by anikalindtner** [comment]
@alicetragedy I've updated the gist and added the fifth tab in the screenshots and the text.

**Comment by alicetragedy** [comment]
@anikalindtner strange, I can't access the images. sadface :(

**Comment by anikalindtner** [comment]
@alicetragedy sorry! should work now. could you check pretty please?

**Comment by alicetragedy** [comment]
it works!! 

![tumblr_m9dlcwp2yr1qiyseco3_250](https://cloud.githubusercontent.com/assets/3143348/13770664/feb68826-ea88-11e5-8d69-3281b31296ee.gif)

**Comment by carpodaster** [comment]
@alicetragedy This has been closed by #426, right?

**Comment by alicetragedy** [comment]
yes! <3
