### ISSUE TITLE
Applicants should not be able to add more than 3 conferences

### ISSUE THREAD

**Issue by Nattivolk** [rails-girls-summer-of-code/rgsoc-teams#414]
Conferences, it says an applicant should only add max 3 conferences. I could add many more conferences. If 3 is a hard limit, maybe we should not allow adding more?

**Comment by Nattivolk** [comment]
Probably on hold due to https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/411
But important as soon as we open the conferences again afterwards

**Comment by alicetragedy** [comment]
:+1:

**Comment by alicetragedy** [comment]
For now I've set it so that editing the conference stuff in the profile is not visible until the season starts (July 1st) so we have a little bit of time to get it fixed. thanks for noticing & creating the issue!

**Comment by F3PiX** [comment]
Copied from PR 414
I worked on a solution that:
- sets a limit to the number of permitted attendances (in the `accepts_nested_attributes_for` method)
- Hides the 'add conference' button for users who has already 3 attendances saved to their profile   
- Adds an flash alert when users wants to save their profile with more than 3 conferences.
The count of the attendances is updated only when the parent is saved. This means an user is able to add 4 conferences in the Edit Profile form, and will not be notified that 3 = max until after submit.
This is not super user friendly.

I stopped working on it, because but I am having second thoughts about the server side. It is making the code less flexible and more rigid, for no good reason.
Now I think it would be better to solve this at the client side with some nifty javascript. The current 'Add button' is probably built in by the nested_form gem. It must be possible to make it check for the number of attendances as well.
 
Feedback and suggestions are very welcome.

**Comment by alicetragedy** [comment]
Note: I've removed this from the application process as I think it's not super important for now. It's enough if this gets solved before the start of the program!

**Comment by carpodaster** [comment]
Makes sense, thank you! 💟

**Comment by klappradla** [comment]
Closing this as this is solved via introducing the `ConferencePreference` model.

<img width="1035" alt="screen shot 2017-08-20 at 16 30 10" src="https://user-images.githubusercontent.com/3491815/29495750-7d829cf2-85c5-11e7-9d31-cc4d5615d296.png">

**Comment by carpodaster** [comment]
🎊
