### ISSUE TITLE
Student Dashboard/information hub

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#462]
Originally created by @alicetragedy on July 21, 2015. Moved from the orga TODO list. It was discussed at length during the [orga call on July 15th, 2015](https://github.com/rails-girls-summer-of-code/organization/wiki/Weekly-call:-minutes).

---

As of now, we have no specific place where we put information that is relevant to **selected students only** – only a spot (the website) where we have the application guides. 
I feel there should/could be a separate spot, ie. in the teams app, where we provide additional information for the students such as instructions on creating a blog post and pull request, instructions for the conference raffle, etc..

There are several possibilities:  
1. to move all information like this to the help section of the teams app
2. to create files for each instruction set in the `summer-of-code` or `rgsoc-teams` repos, and link to them from the teams app (eg. from the help section)
3. to create a separate repo for students, which they will have access to
4. to move all such information to the website and make everything completely transparent

There are pros and cons to each possibility, but I would prefer going with either 1. or 2. as I feel that:  
- the teams app is the right spot for such information
- a separate repo would be YET AGAIN another place they have to check regularly, which might overwhelm students
- some of the info is not relevant for applicants or "outsiders", so the website just doesn't seem like the right spot for it.

**Comment by agnik5** [comment]
@carpodaster This is the second issue I'm thinking of working on if it fits you.

**Comment by carpodaster** [comment]
@agnik5 sure! Please also check #60 and please ping @katrin-k for design implementations (I'm closing #60 – let's continue the discussion here).

**Comment by agnik5** [comment]
@carpodaster @ramonh @katrin-k Sorry for not commenting in this thread for some time. Now I'm back to this issue. Could you please give me more details about your requirements. How is this issue related to #136?

**Comment by agnik5** [comment]
@carpodaster @ramonh @katrin-k My another question arises from differences between #462 and closed #60. In the first case it's a matter - as I understood - of a place, where student will be able to find current info on what's going on in RGSoC. The latter concerns roles other than student's.

**Comment by katrin-k** [comment]
I just realize, the reference to #60 is a bit wrong. (Especially the name is misleading. Since I did that back then: Sorry!). 
So: Issue #60 started what is now the supervisor dashboard => implemented via #109.
And yes, @agnik5 you're totally right. The latter concerns other roles. 

Issue #136: @ramonh This is about removing the data from 2015 and moving it into its own place, isn't it? If yes, this is not related. 
@agnik5 We do that every year, so stuff is archived and the organizers can look up previous information. 

#### So the important bit for the student dashboard is:
"there should/could be a separate spot, ie. in the teams app, where we provide additional information for the students such as instructions on creating a blog post and pull request, instructions for the conference raffle, etc."
==> We have several wiki entries, old blog posts, guides on the public website, gists… with How-To's for the various activities/requirements that you students will to do. 

I agree. We indeed need to define the page a bit better. 
My proposal for the basics is: 
- Organizers can create/edit/delete entries
- An entry consists of a title, a description text (editable with Markdown), (multiple) file attachments, an extra URL field, a category, a state (draft/ready) and visibility (visible for students/not visible). *Is sth. missing?*
- Students will see only entries that are visible and ready. 
- Organizers see all entries of all statusses. 
 - In the menu: ??? I'd suggest to put it under the same "Dashboard"-item as the supervisor board. However, there needs to be a solution for users being both organizer+supervisor. 

That's not complete yet. @agnik5 Since you are a student, you probably also have some ideas. E.g. there could also be an announcement area…

**Comment by agnik5** [comment]
@katrin-k Thank you very much for clarification, it helped me a lot.

I'm thinking about the features right now. What came to my mind immediately is:

- I'm not sure, if "Help" section will be a proper place for this features. Especially as it's not very visible now and student may not catch the idea to look for instructions there. "Help" might become a part of such dashboard.
- As you wish to make a single place for all info concerning students - instructions, as well as announcements / big 'yes!' to that ;) /, I agree, that "fully-fledged" dashboard would be a good option. Divided to at least those two categories.
- To guarantee, that nobody will overlook some announcement, there may be some option to send notification to roles concerned while adding entry. But I'm not sure if I'm not overcolouring ;)
- You wrote that there may be cases when organizers don't want entries to be visible to students. Did you mean just when they're not ready to publish? I'm thinking of adding an option to define a time, when some earlier prepared entry has to become visible. But again - not sure if I'm not overcolouring ;)
- "there needs to be a solution for users being both organizer+supervisor" - what do you mean exactly?
- When adding an entry, there may be a tick list to select roles, for which some entry should be visible. But it goes beyond the scope of students' dashboard I guess.

What do you think about it?

**Comment by ramonh** [comment]
@katrin-k Sorry I'm a little confused, why would that issue involve removing data from 2015? If I understood correctly it proposes looking through the app for more roles' namespaces. For example, the `supervisor` one has been added in the meantime.

@agnik5 I think Katrin meant that it would be good to have a dashboard for being both a supervisor and an organizer. Maybe two dasbhoards on the bar? Not sure.

Having said that, a centralized area for news and other student-related daily things is a worthwhile endeavor.

**Comment by agnik5** [comment]
@katrin-k @ramonh If I understood you right, the task contains 3 components:
- building a students dashboard, where they will be able to access info like instructions and announcements
- modifying an orga dashboard adding option of adding etc. new content for students
- find a solution, thanks to which a person, who is orga and supervisor at the same time, could see all the content they're authorized to access due to both roles?

**Comment by F3PiX** [comment]
@agnik5 Did you see the supervisor's dashboard? (Team Cheesy added that last year :-) ) It might help clearing things up. I thought the student dashboard is meant to be something like that, but don't take my word for it, ask your mentor :-)  
 
AFAIK orga's have full access to all the namespaces. So orga's would need access to write to all the student's dashboards at the same time, while one student only has access to her own dashboard. I think this can be done with a setup similar to the current conferences: only orga's add them, and they show up on several places in the app. So, IMO you don't need to build an orga dashboard as well. Again, don't take my word, ask your mentor. 
The supervisor/orga combination is a thing. You probably don't want a supervisor to read her student's dashboards. Nice challenge: how to deny orga's access to the teams they are supervising. If that is possible at all.

**Comment by ramonh** [comment]
Good points being discussed here!

A question is: Would/should organizers be able to write different 'notices' for different teams, or would it be more of a program-wide announcement system? If I understood correctly, there seems to be a consensus that this would be overkill.

Having said that, @F3PiX raises a good point. Since they have access to everything, an organizer could just write an entry in the page for students' dashboards and it would eliminate the need for a organizer dashboard if it's going to just be for adding entries.

**Comment by ramonh** [comment]
Also, I like the idea of a Help section a lot, @agnik5! Maybe a link that says "Helpful Links" or something like that. What do you think?

I think this would be good as a separate link, maybe above the list of announcement entries.

**Comment by agnik5** [comment]
@ramonh And another point is that if it's only about linking general info / instructions / announcements /not specific to particular teams/, will there be a need to block it from access of supervisors.

As for the 'Help" section, I didn't mean I'm against it, but at the moment it's linked at the bottom of the site with small font. So it's not so easy to find ;) I agree that it would be nice to have both announcements sections and instructions section, 'Helpful links' is a nice name for the latter :)

**Comment by ramonh** [comment]
I'm glad you agree, @agnik5! 

If it's unspecific to teams, I don't think there would be a need to block supervisors from it

**Comment by agnik5** [comment]
I guess a nice thing would be a preview function for team status updates.

**Comment by ramonh** [comment]
@agnik5 You mean the daily logs, right? If so, that's a good idea!

**Comment by katrin-k** [comment]
hey y'all. sorry for being so quiet. I was away for a long weekend. 

Regarding the namespace-stuff: Sorry for the confusion. Apparently I completely misunderstood this issue. :dizzy_face: 

As to the basic purpose: Yeah, I also understood it as being "merely" an announcement/helpful links section. Including the current Help page has a big +1 from me. 

As to the other ideas + questions:
- There's no overcoloring in collecting ideas! :D 
- Visibility of entries: Upsi, that was obviously a bit confusing. Indeed, I meant it as "make visible for students now". The automatic timer function is a great idea. 
- Supervisors should also be able to see what the students see, since students will likely refer to infos from that dashboard. 
- The organizer/supervisor distinction: That came from the naming of menu item links. There's a menu item "Dashboard" that's currently holding the Supervisors' Dashboard. And since this issue is called the Student Dashboard (filled with content by the organizers), I was thinking of using just 1 menu item "Dashboard" for both, that could then have a sub-navigation for users who are both organizer+supervisor. This is also related to #380. @ramonh As we already talked about it, I feel it makes sense to really approach issue #380 soon :). But we might also simply go for a tabbed content page where the supervisor dashboard is then only shown to the authorized users.  
- The preview of team status updates: @agnik5 Same question, you mean the daily log? If so, that would rather be a separate issue, wouldn't it? (and yeah, good idea :).)

**Comment by F3PiX** [comment]
* Not sure if it is a good idea that the supervisor has full access to the student's dashboard. I would say: the dashboard is a private place for the students. I can imagine that some of the info provided by the orga's, shows up on the supervisor dashboard too. 
For shared info, like links to instructions, it would be extra super important to pay attention to the _naming_ of instructions etc.

* Preview team status updates. Kinga, or do you mean write/preview tabs to preview marked down text? That sounds GREAT! In both cases: Why would you want that in the dashboard, and not in the existing status_update_input form? The status updates also show up in the Team page. That is 2 times already. I think showing them on more than 2 places quickly becomes confusing.

**Comment by agnik5** [comment]
@katrin-k Yes, I meant daily logs indeed, I wrote 'status updates' after the naming used for this in app. It would be helpful to check how a log looks after adding markdown /yes @F3PiX :)/ etc. I was also thinking of the option to save a draft. It my be useful for situations when teammates don't have the opportunity to prepare a log together. For example one teammate writes about her day, saves the draft, and the second teammate adds her part and publishes the whole log.

@F3PiX Sorry, what I wrote may have been a bit confusing. I didn't mean taking daily logs out from where they are at the moment. I just thought that current menu visible after logging in as a student has to be a part of the dashboard. I'm not sure now if I correctly understood the idea of student dashboard.

It seems that one of the main tasks for us is to agree on the /in/visibility of student dashboard for supervisor. A starting point would be answering to question: what exactly this dashboard is expected to contain :)

**Comment by F3PiX** [comment]
I don't want to add to the confusion ;-) Sorry.
Last year we built the supervisor dashboard in an agile/iterative way. So we started with one basic feature, I think it was just the links to the supervisor's own teams. And added another feature in small steps/iterations, step by step. You should ask your mentors and coaches if they agree on working that way, if you would be interested. 
Also, we did a small survey in Slack, asking the supervisors a few questions about their work and workflow in the app, to get a feeling for the most urgent features from a user's point of view.

**Comment by agnik5** [comment]
Nice idea, I'll ask about it.
I also did a small survey in Slack within students, hope to get some feedback.

**Comment by ramonh** [comment]
A small breakdown that this would involve (please feel free to suggest tweaks!):

- [ ] Adding the student's dashboard page and add routing
- [ ] Adding the link (or form) to add a daily log
- [ ] Adding a "Help" link or a set of important links
- [ ] Adding a list of announcements
- [ ] Giving organizers a place to write said announcements

**Comment by agnik5** [comment]
The first two items are done.
![screenshot from 2016-08-04 16-39-42](https://cloud.githubusercontent.com/assets/12581810/17406021/16f2b556-5a62-11e6-86d0-6feeadfac173.png)

**Comment by ramonh** [comment]
Awesome @agnik5 ! Feel free to tick the boxes as you go

**Comment by agnik5** [comment]
Under the "Status Updates" there are the same things as were before, just the link is moved from main menu to dashboard. We can 
- leave it as it is or 
- treat the "Status Updates" as a list of posted daily logs and then add a form for creating a new log to the Dashboard
or...?

**Comment by agnik5** [comment]
As for
3- Adding a "Help" link or a set of important links
4- Adding a list of announcements

I think that:

ad. 3: the full list of links should be in the separate view, but in the dashboard there can be some most important or latest added
ad. 4: as above, but here there **should** be sth like feed of the newest / current announcements /where deadline didn't passed/

**Comment by agnik5** [comment]
- [x]  Adding the student's dashboard page and add routing
- [x]  Adding the link (or form) to add a daily log
- [x]  Adding a "Help" link or a set of important links
- [ ]  Adding a list of announcements
- [ ]  Giving organizers a place to write said announcements
- [ ]  Making the dashboard the default landing page for students (?)

**Comment by agnik5** [comment]
![screenshot from 2016-08-10 15-41-23](https://cloud.githubusercontent.com/assets/12581810/17555742/fb2d534a-5f10-11e6-884f-f51a1e0fc07d.png)
![screenshot from 2016-08-10 15-41-42](https://cloud.githubusercontent.com/assets/12581810/17555743/fb32508e-5f10-11e6-87d5-b34283954776.png)

**Comment by agnik5** [comment]
Notepad added :)
![screenshot from 2016-08-12 09-49-08](https://cloud.githubusercontent.com/assets/12581810/17615984/20bab636-6072-11e6-8b62-6e181ff55692.png)

**Comment by alicetragedy** [comment]
It's unclear whether or not this is still a WIP or if it's been dropped (or implemented). @carpodaster do you have any idea about this?

**Comment by F3PiX** [comment]
I'll close this and open a fresh new issue for Summer of 18.
