### ISSUE TITLE
Suggest a conference feature

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#472]
Students can choose a conference from our list in their profile. However it's possible, that there is a cool local conference which we don't know about. 

![screen shot 2016-06-23 at 23 11 45](https://cloud.githubusercontent.com/assets/1745735/16320648/32647eb2-3999-11e6-96f7-d536125f4926.png)

I think we should add a text field where a student can suggest a conference.
Something like "Here you can suggest a conference you would like to attend as a part of the RGSoC program" [text-field].

In `rgsoc-teams/app/views/users/edit.html.slim`: the field should be available regardless the conditions: `- if current_season.started?` and `- if Conference.any?`

In `rgsoc-teams/app/views/users/show.html.slim`: the field should be displayed regardless the condition `- if @user.conferences.any?`, but there should be another condition (that the field if filled out).

**Comment by anasofiapinho** [comment]
Are you saying that you would just have a text field and not the checklist nor the button? If that is the case, I agree with you @mkalininait. I like to make things simple and stupid in forms, even though it will be a bit harder for us to process the information afterwards. If this makes any sense, I would suggest we just put a link there to a web page/github issue that had a list of conferences we know, in case the students don't know any or would like to get some ideas.

**Comment by carpodaster** [comment]
I'm not too familiar with the conference raffle logic, but I believe we need actual database records, referenced by an ID for it. I can imagine that having just a free-form text input makes things very tedious during conf raffle round 1 + 2

**Comment by mkalininait** [comment]
@anasofiapinho @carpodaster I didn't actually mean to remove the dropdown. My suggestion was to add a text field *in addition* to the dropdown. Sorry, I probably didn't make it clear enough.

How I understand the current process: 1) we find interesting conferences around the world and in teams' locations; 2) we contact organizers and arrange diversity tickets and lightning talk spots (if possible); 3) we make a list of conferences who accepted our request; 4) we make a conference raffle.

The reason why I proposed to make an additional field is that there, on the step 1, we might not know about all the interesting conferences, especially local ones. My proposal is to make students suggest conferences they'd like to attend, so that we could add them to our list and process on steps 2-4.

**Comment by anasofiapinho** [comment]
@mkalininait That is fine too. :) Like I said, I am up for removing the button because I takes away one step from the process.

Let me know if you want me to work on the database of the conferences, with all the fields of the database like @carpodaster spoke about or if there are any other changes.

**Comment by mkalininait** [comment]
@anasofiapinho I'm not sure I understand you. Why would removing the button take one step from the process away? Could you explain please? 
What this button does, it lets you choose yet another conference from the list for the conference raffle.

**Comment by anasofiapinho** [comment]
Hey @mkalininait, I just didn't understand how it worked. I should have asked to try it before giving my opinion. Sorry for taking your time.

So, this means that there is a "block" containing the dropdown, the link "Remove" and the button "I want to add another conference". Every time you click on that button it will duplicate that block allowing people to add another conference or remove it if they click on "Remove". Just like the "Roles" "block" on the users' profile, right?

Yeah, I agree with you. That text field is helpful after those blocks.

**Comment by carpodaster** [comment]
`/conferences` already offers a link to create a new conference for admins. I would rather re-use that … with a bit of tidying up (ie. moving the hardcore conference editing into the orga-namespace).

We can add a `proposed`/`accepted`/`rejected` state-machine to conferences just like we have for projects. That would mean a conference created by an admin (from within the orga namespace) is automatically accepted, admins get an email when a conference is suggested by somebody else. Open question: who is that somebody else? Anyone registered? Members of accepted teams?

How does that sound in general, taking the suggest-a-conf feature out of the form, that is?

**Comment by anikalindtner** [comment]
@mkalininait I think having a simple text field that then creates a list of conferences for us, might be a good idea. Nothing too complicated to make it work for this year I'd say. Depends on who wants to take this on, though. I'd say: the goal is for the organizers to have a list at the end of the day of conferences that we can contact. That's also possible by them telling their supervisors and the supervisors filling out that list, if no technical solution is easy enough. But from my side there are no strong opinions. If you want to take this feature on and you think, a text field might be the best, then sure, go ahead! 💪  I don't care too much about the consistency of the logic, since we might have to change / remove that feature anyways in the future.

**Comment by carpodaster** [comment]
> since we might have to change / remove that feature anyways in the future. 

@anikalindtner do you mean the conference feature? Can you elaborate on this a bit? This has some implications on currently open issues. 

Other than that: I do have strong feelings against adding it to the `User` model. Yes, it is easy to add a db column, but in my book, suggesting a conference has nothing to do with a user. If we want to go for the least amount of work: why not just send an email?

**Comment by alicetragedy** [comment]
To answer your question @mkalininait, we do two raffles in the summer, that's why we have "conferences (1st round)" and "conferences (2nd round)". This means any conference added to the "1st round" will be visible for the students and will be a conference they can apply to for a free ticket. 

I agree with @carpodaster on adding the conference to the `User` model. I don't think that just because it can be done, it should be done ;) Not caring about the consistency of the logic is exactly what leads to big apps that are super difficult to be maintained, and I'd rather avoid that.

When I first suggested that we ask students for local conferences they would like to attend, I saw it more as a "student tells their supervisor about a conference" type of situation, not an extra feature in the teams app, for the simple reason that we don't actually have an exact plan of how this would work, and adding a feature that has been poorly thought-through is imho worse that adding some of the conferences manually into the teams app. Before having the suggested conference in the list of conferences students can apply to, one of us needs to contact organisers of the conference anyway and have the free ticket approval; so at the end of the day, I don't think having it in a text field in the app or in a list supervisors send us would make much of a difference.

**Comment by mkalininait** [comment]
Thanks for your input @anikalindtner @alicetragedy 

You won @carpodaster :) We can make a proper feature. It looks to me though, that it won't be ready for use in this season. WDYT? 
If this is the case, would it be possible to ask supervisors ask students about preferred conferences - as a solution for this year? @anikalindtner I can provide a google form or a spreadsheet for that.

**Comment by mkalininait** [comment]
FYI: I'm going to send an email to students and ask them to suggest a conference for this year. 
But may be we need a proper feature for next years.

**Comment by klappradla** [comment]
Isn't this already part of the conferences milestone @mkalininait ?

**Comment by mkalininait** [comment]
@klappradla Yes! And it's already implemented <3
I'm closing this issue. Feel free to reopen it, if you think that something still needs to be done.
