### ISSUE TITLE
Daily log reminder even when daily log is present

### ISSUE THREAD

**Issue by Althaire** [rails-girls-summer-of-code/rgsoc-teams#512]
My team fills out their daily logs on their blog and it gets fed into the teams app. I can read it on the same day it's "due" on the teams app, but they get an email reminder every day nonetheless.

The easy solution would be that they just fill it out on the teams app. I think it would be a huge shame that they abandon their blog (which they can continue to use even after the summer to track their progress) and even more of a shame if we are the ones to encourage them to do so.

The other solution would be that they just copy paste it off their blog, which is a hassle. 

I think the best solution would to find out why the teams app doesn't recognize this feed and sends them the email even though the log is there, on time, on the app, available for everyone to read 😄

**Comment by anikalindtner** [comment]
@Althaire the thing is that the feed for the blog isn't as quickly updated and recognized by the app as the log entries directly in the app, so the bot thinks there is nothing there.

(@michaelem might have some more technical details here)

so if they decide to do the daily logs on their blog, they have to live with getting a notification every day. one of the only thing that we ask students is to do their daily log and if they want to do it in a special way, they have to deal with the fact that this is not the best solution for them. that's how it is for now. 

in the future we might be able to look into that and see if there is something we can do. since they are the only team doing it this way, i don't see this as a high priority for now, i'm sorry.

**Comment by F3PiX** [comment]
It may be that the scope `without_recent_log_update` doesn't take the blog into consideration right now. If we can solve this by adding the `kind: feed entry` to the scope, it would be a small adjustment. 
@michaelem WDYT?

**Comment by carpodaster** [comment]
Not in front of a computer right now but I believe this can be fixed with minimal effort: I think blog updates will be created as `Activity` records once fetched. The reminder logic would probably only have to take activities of `kind` feed (don't know the exact value) into account as well.

Von unterwegs gesendet.

**Comment by Althaire** [comment]
@anikalindtner I know, sorry to bother with this issue 😅  I was going to say but I didn't want to make the comment too long: they don't mind the emails. It's more of a "by the way, this happens" more than "urgent help needed!!" (Also, I think that they were worried that the emails might leave some sort of mark as if they weren't doing the logs, so they checked up on this with me)

No problem at all, thank you! 😄

**Comment by F3PiX** [comment]
Hi Pilar! Just checking.
1) In your Supervisor Dashboard, the blogposts should be listed as updates under 'Activity'. Are they?       
![schermafbeelding 2016-07-28 om 21 37 53](https://cloud.githubusercontent.com/assets/6314687/17226821/9d2d958e-550b-11e6-85a0-a6ec603fe3ba.png)
