### ISSUE TITLE
Check + improve button styles

### ISSUE THREAD

**Issue by katrin-k** [rails-girls-summer-of-code/rgsoc-teams#524]
As mentioned by @alicetragedy in #352, the button group thingy on team/show is a bit unfortunate. Also, I found the button styles are not always used consistently (e.g. "submit a project" is grey, whereas "new team" etc. is blue). Or for projects/edit, the "Cancel" button is missing. 

I'll go through the pages and adjust those. 
In the process I might also come up with a proposal for new colors.

**Comment by katrin-k** [comment]
What I did so far in commit https://github.com/rails-girls-summer-of-code/rgsoc-teams/commit/dcd7aac917601814e2db707545e1416c20fcfbbf
I used the existing BS button styles for the various cases:

#### `.btn-primary`
New team, new project, new … 
==> Everything that's newly created

#### `.btn-success`
Save, send mailing, save/update status update, save comment, … also: join team
==> Everything that saves sth. and is then (kinda) finished.

#### `.btn-info`
Edit stuff, add a source/member/conference/role (since it's part of editing whatever profile), link to my team, save application draft (not green since it's not finished and still in the process of editing)
==> Everything that is part of editing sth. 

#### `.btn-warning`
Email a team, Tweet about conference
==> Everything that sends out messages to outside the teams app

#### `.btn-danger`
Reject project
==> Scarcely used. 

#### `.btn-default`
Delete, remove, cancel
==> All the "negative" stuff

**Comment by katrin-k** [comment]
And here's what I did to the colors. Disclaimer: I'm not a good visual design person. So I took the colors and simply used less "screaming" hues. Plus, I removed the gradients, so the buttons look more flat now. 
Overall, I think it's ok. But plz look at the last pic… this needs inspiration.

==> An add button
![524-button-add](https://cloud.githubusercontent.com/assets/2246045/17562573/b72238e4-5f2b-11e6-8f34-860a7c6556c1.png)

==> A save/cancel combination
![524-button-save-cancel](https://cloud.githubusercontent.com/assets/2246045/17562571/b721a6fe-5f2b-11e6-9e0a-6facd8723c2f.png)

==> An edit/cancel combo
![524-button-edit-cancel](https://cloud.githubusercontent.com/assets/2246045/17562572/b7221882-5f2b-11e6-8e11-66ec758a7d96.png)

==> A new… button
![524-button-new](https://cloud.githubusercontent.com/assets/2246045/17562574/b7232f60-5f2b-11e6-840c-0cdd754b5acf.png)

==> That… is a lot more screaming now :(. Currently, those buttons are `.btn-default`und thus grey. I'd like to use the colors here since they convey a message, but I don't know… Any ideas?
![524-button-edit-mail](https://cloud.githubusercontent.com/assets/2246045/17562575/b730fa3c-5f2b-11e6-8475-754bc7423a8e.png)
For comparison, the page in large:
![524-button-edit-mail-lrg](https://cloud.githubusercontent.com/assets/2246045/17562708/4fd3b432-5f2c-11e6-9350-5ac6aa765d0c.png)

**Comment by ramonh** [comment]
Hey @katrin-k, WOW, this is awesome. Thank you!

I immediately prefer it over the gradients from before.

My one feedback would be to see if it's possible to make the contrast between the button background and border stronger? I feel they're a bit too close, particularly on the orange buttons

**Comment by inescoelho** [comment]
The white text in those bluish buttons (like the "I want to add another conference" button) seems a little hard to read for me, it gets kind of blurry.
But I like the flat - appearance :)

**Comment by katrin-k** [comment]
@inescoelho good point! I'll double-check on my large screen, too. My laptop is usually displaying things crisper than on many other screens. 

@ramonh possible is everything :). I'll see which colors I can find.

**Comment by F3PiX** [comment]
I am not totally convinced regarding the colors. As RG Red is leading, I think it is very hard to combine that fully saturated red with less saturated colors. Regarding the Bootstrap range from succes to danger: I think most of the time it is sufficient to differentiate between the primary choice and secondary choices. I think between all of us we can cook up some other options. How about that? Wdyt @katrin-k ?
What I DO like very very much is the consistency and the style guide for use cases!

**Comment by alicetragedy** [comment]
My two cents on this: I also like the idea of flattening the buttons, so I think we should definitely go along with that! Love it 👍 
Regarding the colours: green, red and blue send very strong messages, and from a UX point of view, I don't think it's a good idea to stray from these "primary" colours. Turquoise or orange don't really have a "universal" meaning, and it could quickly become confusing and messy. I would suggest sticking to one or two colours (green and red) for straight-forward, important actions, and having all other more "neutral" buttons in grey. If we *really* want to make huge changes to the button styling, I would keep that for after the program: we are thinking about a redesign for the website connected to a possible rebranding already, and could work on possible colour schemes and, of course, on a style guide so the styles are consistent across the app and the website.

**Comment by katrin-k** [comment]
@F3PiX I see what you mean and yeah, I agree, the header color is indeed very strong. I've played around with outlined buttons, that only get a background-color on hover. Makes things way less disturbing. (below are screenshots)

@alicetragedy also brought in a good point. Since any rebranding affects both teams app and website, it totally makes sense to work on both of it together after the program ended and avoid bringing in new styles every other week. 
(It's just… those buttons… :D *scnr* )

Screenshots with outlined buttons.
![524-edit-add-email](https://cloud.githubusercontent.com/assets/2246045/17582544/c08a7082-5fac-11e6-8624-0c4e3ab1b544.png)
![524-edit-cancel](https://cloud.githubusercontent.com/assets/2246045/17582551/ca6d3526-5fac-11e6-885b-7923e65c7f6b.png)

**Comment by klappradla** [comment]
I agree with @alicetragedy. However @katrin-k, concerning colors and inspiration: I'm personally bad with coming up with color schemes, so I usually use tools for that. I can highly recommend [coolors.co](https://coolors.co/) - you can also import images there to extract a color scheme.

Besides that (cc @ramonh 😂 ), there's [bootflat](http://bootflat.github.io/), an extension to bootstrap, *"flattifying"* it. You can also look at their button design + colors (I think they're both pretty good).

**Comment by katrin-k** [comment]
@klappradla uuh, http://coolor.co looks indeed very promising. Nice! What I often do is take one first color and then check out the complementary/triadic colors on http://www.colorhexa.com.

**Comment by troubalex** [comment]
I find complementary colours always difficult to work with, they come with a very strong contrast. You could try with one of the blues from [this triad palette](https://color.adobe.com/create/color-wheel/?base=2&rule=Triad&selected=2&name=My%20Color%20Theme&mode=hsv&rgbvalues=0.5470588235294118,0.03140522875816991,0.03140522875816991,0.8725490196078431,0.8638400352175996,0.2246005809731299,0.8470588235294118,0.13333333333333333,0.13333333333333333,0.037145969498910636,0.4116538623247542,0.6470588235294117,0.05875816993464046,0.3585919045981745,0.5470588235294118&swatchOrder=0,1,2,3,4). Another great resource for palettes is [Dribble's colour search](https://dribbble.com/colors/d82222?percent=20)

But as pointed out above, I really wonder if it is necessary at all to add more colours given that the red is *very* dominant. TBH, I'd simply keep them grey. You could play with shadows and darker greys (or red font) on hover.

Useful resource: https://www.smashingmagazine.com/2016/04/web-developer-guide-color/

Also, there are so many buttons on that page, that they have more of the function of a toolbar, rather than primary/secondary/whathaveyou actions. Another argument for reducing colour.

And then I have some nitpicks:

+ Something is not quite right with the drop shadow. It should at least have 0px on the x-axis but I suspect there is room for improvement on colour, size, and blur as well.
+ I don't like the black(-ish) border between the button groups. I'd suggest making that the same colour as the button border.
+ The button for deleting the profile looks disabled. I suggest setting the font-color to the usual text color, rather than a lighter grey.

**Comment by troubalex** [comment]
PS:

>Since any rebranding affects both teams app and website, it totally makes sense to work on both of it together after the program ended and avoid bringing in new styles every other week. 

Would that really be a big deal if the designs of the web site and the team app diverge for a little while? I'd personally land the redesign first, and then get to porting it over to the team app.

**Comment by ramonh** [comment]
The white button with outline looks great too!

**Comment by F3PiX** [comment]
I like the outlined buttons too. The staple of fairly unrelated actions/buttons is an issue. I wouldn't mind if we don't wait for the redesign to solve this. It seems to me more of an UX structural thingy, and in my book it is never too early to solve that :-)
Maybe some buttons can move a bit? Like the 'add source' could move to where the sources are listed?
Also, I would love to think about the wording of the buttons.

**Comment by katrin-k** [comment]
kchchch… this issue turns out to be a great resource for color choosings ;). 
@troubalex thanks a lot for the smashing mag link. this is really a hugely useful article. 

When I look at the whole thread here, I see 2 basic aspects coming together:
1. A new visual design (branding) lurking at the horizon
2. Tons of UX issues

Re 1. I feel like leaving the button-dabbling for now and wait for a sincere visual design overhaul. 
The thing is, though, it'd be awesome if this could happen rather soon-ish (= in the upcoming months, especially when I look at #35 being from 2013… ;).). Buuut, this brings in the problem of who can do it :). 
@alicetragedy Are there already specific plans for this?

Re 2. IMO, it makes more sense to work on those UX thingies. For the buttons, those are the placement, the wordings, etc. But also other things like duplicate form fields (#184) or improve display of information (as in #83). (New visuals can easily be put on them later on.)

So all in all, having opened the box of pandora ;D, I'd suggest to close it again. What do you all think?
What I also take away from this dabbling is, it's delightful, but it's surely better to focus on existing issues than opening up new ones.

**Comment by F3PiX** [comment]
+1 to focus on the UX thingies for now. 
+1 on closing this one. I wouldn't say that you should not open a new issue if something is bugging you. (Just be prepared that once in a while you will open a box of Pandora.) IMO this discussion produced useful information, albeit not the intended button overhaul. :-)

**Comment by alicetragedy** [comment]
Thank you @katrin-k for summarising it all so well. The primary issue I had with buttons (specifically on the team pages) was less of an aesthetic issue and more of a UX/functionality issue — that button group looks strangely stacked on mobile devices, and I think this should be fixed. 
A big chunk of the teams app is really not created with mobile in mind, and since our audience is global, meaning they will be accessing the teams app from any device possible, I see this as a bigger issue than i.e. the colour of the buttons. I see trying to make everything mobile-friendly as more of a priority than making the interface more harmonious (even though I would really like to get to that point as well).
I would suggest focusing on the UX things you mentioned, and keeping a new styling of buttons, etc.. for a possible redesign after the summer.
There are no concrete plans for this, and it's something we need to discuss as an organisation, but there was the idea of rebranding and moving away from the name "Rails Girls" as it's become increasingly focusing for people who stumble upon our website. This would mean a change in our name, but also possibly moving away from the RG imagery and possibly changing the color schemes, etc.. As you see it's a really big job, and I think that at that point, rethinking the kind of interface we want for the teams app (maybe something cleaner, introducing flat buttons, etc..) would make sense. But: this is nothing concrete YET, I would just see the end of the program as a good possibility to get started (i.e. October).
