### ISSUE TITLE
Unsure if money is involved or not (like in GSoC, or Outreachy)

### ISSUE THREAD

**Issue by jancborchardt** [rails-girls-summer-of-code/rgsoc-teams#566]
Heya, awesome you’re doing this, thank you so much! We’ll see to apply with @Nextcloud :)

One question though because that was unclear from reading the website: We participated in GSoC and Outreachy before. For GSoC, Google is sponsoring the students, and for Outreachy the project has to sponsor the students itself (which is no small investment at 5.5k a student).

Is money at all involved in RGSoC? If so, where does it come from? From having no mention of it on the website it seems like no, but I just thought it would be good to clarify this.

**Comment by alicetragedy** [comment]
hey @jancborchardt, cool to see that you're interested in submitting your Open Source project! We prefer getting general questions about RGSoC sent to our contact email (summer-of-code@railsgirls.com) because it's easier to triage and answer so if possible, could you stick to email for all future communication?
Now that we got this out of the way: yes, we offer stipends for students who participate. Our [main website](http://www.railsgirlssummerofcode.org) has a bit more info on this, on the landing page and on our [about page](http://railsgirlssummerofcode.org/about/). I understand the confusion though if you came directly from the Project Submission page, which is on our teams app. Thank you for making us aware of that!
If you have any more questions, don't hesitate to drop us a line. Looking forward to getting your submission! 💪

**Comment by jancborchardt** [comment]
@alicetragedy ah thanks! I was sure I read everything … if the main site wasn’t redesigned in the last few days, I must’ve been on the teams apps the whole time and mainly read the [Help section](https://teams.railsgirlssummerofcode.org/pages/help) there, which also listed opening an issue here as first approach. (Which I also prefer since that was a question I assumed others could have too.)

Thanks for the info then, will use email for future stuff. :)

**Comment by alicetragedy** [comment]
@jancborchardt that's a very good point, and I think we can definitely improve that help section to make it more understandable :) The line "If you think something is unclear or should be improved" pointing to the issue tracker meant to suggest opening an issue along the lines of, "it's not very clear how to sign up for an account" or "I think the help page could be improved" rather than direct questions about the program, however reading it now I'm realising that it could be understood in another way. I will improve the wording there, thank you for pointing this out to us. 👍
