### ISSUE TITLE
User Profile: new fields for coaches

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#609]
This issue originates from this one: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/593

We would like to have more information about coaches to evaluate quality of teams' support.

**Suggested solution:**
1. Add two required fields for users who checked the "interested to help out as a coach" checkbox:
 - "Coaching experience" - multiline textarea field with the placeholder text "Do you have experience coaching junior developers, helping out newcomers to the dev community? Share your relevant experience."
 - "Coaching availability (hours per week)" - numeric field
2. Once an application is submitted, we probably don't want this info to be changed during the selection process. Possible solutions are:
 - "freeze" the fields OR
 - make a snapshot of them and add it to the application snapshot (just as we do with the team members on application submission, AFAIK) <-- looks more preferable to me.

This is a thing to discuss.

**Comment by carpodaster** [comment]
I'm not so much in favor of adding more required fields. Even more so as the "coaching experience" may take some time to fill out – with meaningful data, anyway; you can always get past the validation by entering "I have coached before", effectively providing zero value for us.

I also find it a bit harsh for a person showing their _interest_ in coaching. On the other hand, making it a required field as soon as a user is actually added to a team as a coach gets us back into the merry-go-round of how to enforce the data input.

Afaik, we removed the "hours per week" last year since it is too hard to estimate anyway and it won't safe them from life that happens anyway. The coaches supply no data for the application as of 2016 other than their active confirmation of their status as a team's coach.

**Comment by mkalininait** [comment]
@alicetragedy What do you think about this task? We have two different opinions here :)

**Comment by alicetragedy** [comment]
I think we have to differentiate two things:
- the user profile of a coach offering to help coach a team (in the same way that a coaching company would offer a space), findable through the community page
- the information of a coach attached to a team and an application

unfortunately, these things don't necessarily overlap. Sure, a coach will have the same experience regardless, but objectively, if a coach is attached to, say, two teams we end up choosing, and that in their profile they write down “availability: 40 hours / week” I doubt they'll have 40 hours / week for both teams, if that makes sense. So, I think if we need more info from the coaches in order to rate the applications better, this needs to be done by the coaches after signing up and once they have a better idea of which teams they plan to coach.

I'd be up for adding a single extra field with technologies (similar to the technology / programming language tags we have for projects). We can still think about whether we want the coaches to be more involved in the application process and give them space in the application... but I am not sure if we can or should do it over the user profile?

**Comment by mkalininait** [comment]
Thanks for your opinion @alicetragedy 

> So, I think if we need more info from the coaches in order to rate the applications better

I was thinking that it could be useful for the students when they look for a coach on the community page. Maybe the info about how much time a coach can dedicate to RGSoC can help them make a decision whether to contact her/him or not (together with the info if this coach is already involved in another team or not). What do you think about this use case?

> I'd be up for adding a single extra field with technologies
 
I think this is already implemented for all users in PR #863.

**Comment by alicetragedy** [comment]
As @carpodaster already wrote, “we removed the "hours per week" last year since it is too hard to estimate anyway and it won't save them from life that happens” — so I'd be in favour of sticking to that, and not adding the hours/week again as it's often not really a good indicator of how much time they will ultimately spend on the program helping a team.
I'd suggest to close this issue then, since the technologies bit has already been implemented — I see it as already a good step for applicants to find their coaches through the communities page.

**Comment by mkalininait** [comment]
Ok, closing the issue @alicetragedy
