### ISSUE TITLE
Application form: Mark fields containing info which will be provided to mentors

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#649]
For some reason, I thought this was already done, but it's not. 
The application form should show which fields will be visible to mentors: 

- Why did you select this project?
- Which features are you planning to work on?
- What is your programming level?
- Provide examples of your code
- What you have been doing to learn programming
- How did you get into programming?
- Short summary of your programming skills

Not sure if we should place a notice with a list of fields, have single notices for each field, or add a sentence about it as a `hint` for each field. Thoughts? 🤔

**Comment by mkalininait** [comment]
@alicetragedy Do we really show "How did you get into programming?" (it was not on the list [here](https://github.com/rails-girls-summer-of-code/organization/wiki/Processes:-Application-Process-2017-(design)#other-changes), that's why I'm clarifying).
Do we not show "For how many months have you been learning the language of your primary project?"?

**Comment by mkalininait** [comment]
Maybe we can add notices for the blocks of fields?
 * "Your programming skills"
 * "Your 1st/2nd project choice"

And I'd probably **not** put them in the yellow/blue box (we already have plenty of notes and warnings!), but rather write as a normal text under the title.

**Comment by alicetragedy** [comment]
I've taken the list from the current existing mentor view, we can also make changes to this if needed (but then it has to happen now). I'm also not sure about the “for how many months”, I also feel like we wanted to actually remove that field entirely from the application...? Anyway it's in there now, so we should probably keep it that way and fix the mentor view accordingly. 

I think if we manage to make it so that we share entire “sections” of the form, it would make sense to use a real `notice` element (the yellow or blue boxes) to make it visible — that's what the element is there for. 
if it's single fields we are picking out, it makes sense to have single lines of “normal” text under each label (or each field, depending on how we want to do it) to not overwhelm the user with a bunch of notices scattered everywhere.

**Comment by alicetragedy** [comment]
@mkalininait I had created an issue for the mentor view originally, and I took the list of fields from the doc you linked to — but it could very well be that I missed some or added one accidentally that we didn't want to have in there. Anyway, I'll look at this later today and can make whatever changes are required :)

**Comment by mkalininait** [comment]
@alicetragedy 
**"I'm also not sure about the “for how many months”..."** – there were 2 fields: "For how many months have you been learning since your first workshop" and  "For how many months have you been learning the language of your primary project". We removed the first and left the second.
And the thing is that now we show mentors all the fields from the "Your programming skills" section with the exception of this "For how many months..." which looks strange. 

Re **"How did you get into programming?"**  (the field from the "Background information" section) I have the following concern: from what I remember, students tend to write 'essays' there, which are not necessarily about programming skills. I feel like reading them would take mentors' time for no good reason.

**Comment by alicetragedy** [comment]
good point. I will add the former and remove the latter then 👍

**Comment by mkalininait** [comment]
I've tested this task on production. It seems to be working.
One little issue: 

![screen shot 2017-02-23 at 00 50 37](https://cloud.githubusercontent.com/assets/1745735/23238436/3c9cee4e-f962-11e6-9a08-2e7fcb946890.png)

It's not entirely clear what the unit of measurement is. Maybe rename it to "For how many months have you been learning the language of your primary project?"

**Comment by klappradla** [comment]
Ah thanx @mkalininait !
The view actually pulls all its labels straight from the translation file - so the labels should be identical with the ones in the students' application. Seems there is either a mismatch or some value missing.
I'll reopen and reassign this issue. I'm pretty packed with work at the moment and would forget otherwise...
