### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#655]
Rollbar is full of warnings á la `No route matches [GET] "/favicon.ico"`

Anyone willing to play with a favicon? Personally, I would vote for one that's already rainbow-heart-schemed 😮 `#sneaky` 😉

**Comment by alicetragedy** [comment]
@carpodaster omg yes! finally someone addresses this, I've been thinking about it forever everytime I see the Rollbar warning. We **do** have a favicon.ico already though and it's in `public/images/favicon.ico`. Sorry to rain on your (rainbow) parade 😂 

Not sure why or how it's not being found. Any ideas?

**Comment by carpodaster** [comment]
@alicetragedy oh cool! There is a .png one, the .ico, sadly, is only 0 bytes. The png is very small (16x) and I was told by @axlwaii that you offer several sizes for different devices nowadays. Does anyone have an SVG version of the Rails Girls pixel heart? Or will it be a rainbow parade after all? 😉

**Comment by alicetragedy** [comment]
@carpodaster in that case, it makes sense to create one, apologies! 🙈 
we do have the heart logo as an illustrator file I think ([link](https://github.com/rails-girls-summer-of-code/design/tree/master/logo)); I can look into making it an svg and pushing it so that whoever is interested in this task can take it :)

**Comment by axlwaii** [comment]
http://www.favicon-generator.org/ does a great job creating all favicons you need :)

**Comment by alicetragedy** [comment]
Update: an SVG of our current logo can be found [here](https://github.com/rails-girls-summer-of-code/design/blob/master/logo/rg_heart_logo.svg); @carpodaster feel free to add this in your original comment for anyone who wants to take over this task :)

**Comment by anasofiapinho** [comment]
Hey everyone! I did the favicons of our logo in red and also rainbow colors because I was confused about what you wanted. Thanks @axlwaii for your tip about that website!

### Red logo favicon
The folder is [here](https://github.com/rails-girls-summer-of-code/design/blob/master/logo/favicon-rgsoc-logo-red.ico.zip).

### Rainbow logo favicon

The folder is [here](https://github.com/rails-girls-summer-of-code/design/blob/master/logo/favicon-rgsoc-logo-rainbow.ico.zip).  

### HTML code

In case you wanted, I added the code they suggested here:

```html
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
```

**Comment by klappradla** [comment]
Hey @anasofiapinho I already submitted a PR updating the favicons _(using the red one)_. But I just realized I totally mixed up branch names and issue number with those from work 🙈

I'll clean up the mess and then add you to the PR so that you can have a look.
