### ISSUE TITLE
Selection: you can't rate an application of a team without a name

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#678]
https://teams.railsgirlssummerofcode.org/rating/todos

There is no link to an application without team's name

![joxi_screenshot_1488236110469](https://cloud.githubusercontent.com/assets/1745735/23383773/593d357e-fd48-11e6-8787-98bd1ab823a2.png)

**Comment by alicetragedy** [comment]
Maybe as a quick fix (since some applications might have been submitted with no team name already) we could concatenate the word “Team” with the team name to produce “Team [Team Name]” when the name is present and “Team” when the team name is missing? Just a thought 😅 I'm not sure if there is a better way to do this, we could of course force team names to not be blank and “fix” the already submitted teams/applications manually.

**Comment by mkalininait** [comment]
@alicetragedy I was thinking of the same solution (adding 'Team' to the team names).

**Comment by carpodaster** [comment]
@alicetragedy @mkalininait I'll tackle this real quick
