### ISSUE TITLE
Migrations not running

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#752]
Problem:
Since the upgrade to rails 5.1 in #749  , `rails db:migrate` results in an error, as reported by @michaelem https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/749#issuecomment-304333342 
```
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
  class RatingsAddLike < ActiveRecord::Migration[4.2]
```

I had to run `rails db:schema:load` instead, so I could still use the app.

Solution: 
How should this be solved?  

@michaelem @carpodaster @klappradla

**Comment by klappradla** [comment]
Hey @F3PiX,

thanx for reporting 🙏 

For "resetting" the database, or setting up the project from scratch, I usually do the following:
```sh
# drop the old dbs if there are any
dropdb <dev-db-name>
dropdb <test-db-name>

# set them up fresh including seed data:
bundle exec rails db:setup
```

But yeah, we'll need to come up with a solution for the old migrations as well...

**Comment by F3PiX** [comment]
👍 
I usually do `bundle exec rails db:reset`. Which is db:drop and db:setup in one. Is `rails db:drop`  a different drop than `dropdb` ? 

But still: any ideas for a solution for the old migrations?

**Comment by klappradla** [comment]
`dropdb` is a Postgres command, but probably what `rails db:drop` does under the hood anyways.

For the old migrations, I could either update all of them to no longer directly inherit from `ActiveRecord::Migration` or just remove them. I would personally vote for the latter, since in my opinion the migration files **should not be** the source of truth for a Rails app's database schema. There is the `schema.rb` file under version control and that's the one I care about.

I would however love to have a second opinion on that, since that's simply how I interpret certain features of the framework.

**Comment by F3PiX** [comment]
( PR to squash migrations from last year: https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/381 )

**Comment by F3PiX** [comment]
🌟 🎉
