### ISSUE TITLE
[Conferences] #8: Accepting/rejecting a conference

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#772]
The idea: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/751#issuecomment-308574743
Full list of conference user stories: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/751#issuecomment-309138513

**User Story:**
As an RGSoC orga, I want to know if the students accept our offer or not.

**Things to do:**
1. Who can edit a conf status:
 - Students of the team
2. Who can see a conf status:
 - Students of the team
 - Supervisors
 - Orga
3. Available from:
 - Team view, h4 Conference offers (see Task #771)
4. Next to each offered conference show two links: "Yes, I will attend!" and "No, I cannot attend". You can press one link, but then change your mind and press another one (see how it looked like before: https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/789#discussion_r128508734)
5. Add new fields to the conference export (see Task #770):
 - Conference offer: Value (conference name)
 - Conference offer accepted: yes/no
 - Conference offer #2:  Value (conference name)
 - Conference offer #2 accepted: yes/no
 - etc

**Comment by branquinhoaa** [comment]
@mkalininait How do you think that we can display the conf. status?
I did like this:

![conf-attendance](https://user-images.githubusercontent.com/15239141/29319856-d0dc25bc-81ab-11e7-87e7-ec7687d9aa3d.png)

Will we change the links style after the team had clicked on attend link?

Also, I think we need to merge the PR  #813 in order to finish this one (the export change part).

**Comment by klappradla** [comment]
Just a short note to your screenshot above ☝️ @branquinhoaa: I think it would increase the readability if you'd always add a whitespace 🏳️ between the link and the label.
And for the orga comment, I guess it would make sense to add a linebreak and make the comment a [blockquote](https://getbootstrap.com/docs/3.3/css/#default-blockquote)

For the conference-links: I'd suggest to use a normal [list](https://getbootstrap.com/docs/3.3/css/#unstyled) without bullets (I don't see the point for them here...)

For the attendance-links: they're currently not distinguishable from the conference-links, even though they're a totally different call to action _(they change state, rather then "just" inform)_. It would make sense to have this difference somehow visible, e.g. by making them small buttons instead of just links.

However, I don't see a point in **always** displaying both attendance buttons. What happens when I'm already attending and click `"Yes, I can attend"` again? I guess something like a toggle button would be more obvious here.
And another concern I have with these buttons: for how long should it be possible to toggle back and forth between attending and not attending? _(cc @mkalininait )_ 🤔

**Comment by mkalininait** [comment]
@klappradla We don't set a limit in the Teams app currently. I'm not sure we should make this too complicated. In real life we will probably ask the students to accept or decline the offer until a certain deadline; we don't care what they set in the Teams app after the deadline basically. This is how I see it.

@branquinhoaa In addition to what Max said: please remove the dot from the label "I will not attend this conference". 
I guess we will display the "I will not attend..." label only once the "No, I cannot attend" button/link is pressed, right?

**Comment by klappradla** [comment]
👍  for the deadline stuff. Makes sense @mkalininait.

**Comment by branquinhoaa** [comment]
Hey guys, thank you for all suggestions.
What do you think about it?

![notdecided](https://user-images.githubusercontent.com/15239141/29378832-e784cfb2-8296-11e7-95b1-cc862615c7cc.png)
![attend](https://user-images.githubusercontent.com/15239141/29378830-e77ccd3a-8296-11e7-9414-3c7038947a81.png)
![notattend](https://user-images.githubusercontent.com/15239141/29378831-e7817a24-8296-11e7-9423-c793f1517da9.png)

**Comment by klappradla** [comment]
Yay, looks solid 🎉 

Just came to my mind now: how about adding a tiny paragraph about that both, a `ConferenPreference` and a `ConferenceOffer` is right under each headline? Or is this already "explained" to the students elsewhere (meaning in another view).

I imagine it being something like
> Conferences you would like to attend during your Summer of Code

and maybe
> Conferences RGSoC offers you free tickets to attend during your Summer of Code

_(wording is totally not final, just came up with this right on the spot)_

**Comment by mkalininait** [comment]
@klappradla @branquinhoaa Adding more info is a good idea! I'd actually add more info to both view and edit pages.

Maybe something like:

**Conference preferences (edit form):**
> RGSoC provides the students an opportunity to attend a conference during or after the Summer of Code. Please select one or two conferences you are interested in. In case you don't find it in the [list](https://teams.railsgirlssummerofcode.org/conferences), feel free to add it.

**Adding a new conference:**
> Please make sure that the conference you are adding is tech and has a good Code of Conduct!

**Conference preferences (view form):**
> Conferences you are interested in attending:

@klappradla I'd emphasise *interest* here, because we don't guarantee anything to the students. As much as I tried to make it clear last year, there still were students who said: "Oh, we thought RGSoC would give us the tickets to the conference we chose" in the end :/

**Conference offers (edit form):**
> Please select one or more conferences free tickets to which you would like to offer to the students.

**Conference offers (view form):**
> Free tickets offered by RGSoC. Please accept of reject the offer(s). 

Something like this, but we can of course change the wording.

**Comment by mkalininait** [comment]
@branquinhoaa @klappradla Regarding the orga comments to the conference offers. Tbh, the quote format looks a bit comic to me :) It looks as if it was a wisdom quote or something :) I'd probably vote for the previous version (plain text).

**Comment by klappradla** [comment]
Huuuuge plus 1 for the texts @mkalininait 💚  We need to make things way more clearer upfront. These large forms hardly speak for themselves without any hints to them... 😞 

And for the comment: yes, I looks kinda god-like 😹  also plus 1 for solving this in a not so weird way 😉

**Comment by branquinhoaa** [comment]
What about these?

![teams_edit_orga](https://user-images.githubusercontent.com/15239141/29439760-58015e04-8396-11e7-934e-c7fdd53ff449.png)
![teams_show2](https://user-images.githubusercontent.com/15239141/29439773-6d06a34a-8396-11e7-8ad1-a554703098de.png)
![teams_show](https://user-images.githubusercontent.com/15239141/29439777-6ee9f680-8396-11e7-9633-2262ac53f3ee.png)

**Comment by mkalininait** [comment]
Thank you @branquinhoaa ! <3 I would merge it! 
And we can always improve the UI later if someone has good ideas.

**Comment by branquinhoaa** [comment]
I just love to work with this kind of things xD

**Comment by klappradla** [comment]
☝️ looks awesome @branquinhoaa 👍

**Comment by carpodaster** [comment]
Is this done with the PR merged?

**Comment by mkalininait** [comment]
@carpodaster Yes! 
And I think we can also close this one: #751
