### ISSUE TITLE
Add a CommunityController

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#84]
Currently `UsersController` behaves differently for the RGSoC ramp up phase than it will once the summer has begun. There's lots of commented code.

I'm thinking bringing `users#index` to a CommunityController that displays what we have now. Launching the summer is then a matter of editing the routes file instead of commenting out / in everything (which we'll have to do for 2015 all over again).

Are there other items where the teams app behaves differently depending on what phase we're in?

Thoughts?

**Comment by carpodaster** [comment]
#108 is related.

**Comment by klappradla** [comment]
It seems this can be solved on the way to the new community page 👉  moving this into the [community page milestone](https://github.com/rails-girls-summer-of-code/rgsoc-teams/milestone/13)

**Comment by branquinhoaa** [comment]
@carpodaster we are discussing this issue and we have some questions:
Since /community will be responsible for listing and searching users, we are wondering if it is useful to have an action /users. Can we simply remove it? 
Besides the community link in the header, the path to /users is used when someone calls the 'impersonate' method. The person is redirected to /users. We can change this behaviour, redirecting the person for /user/:id (if you agree to remove the users index).

**Comment by carpodaster** [comment]
@branquinhoaa you are right, I also think we don't need the `UsersController#index` action anymore (the rest of the actions are). Redirecting to `UsersController#show` after impersonation a user makes sense, too! :ok_hand:

**Comment by carpodaster** [comment]
@klappradla @mkalininait we don't really have a Definition of Done for this item, do we? I'm inclined to close this (very old) issue now that #844 has been merged. Subsequent changes (e.g. filters) should be covered by other issues. What do you think?

**Comment by klappradla** [comment]
Yep, would have suggested the same 💚

**Comment by mkalininait** [comment]
Sounds good!
