### ISSUE TITLE
Remove volunteering checkbox from application form

### ISSUE THREAD

**Issue by ramonh** [rails-girls-summer-of-code/rgsoc-teams#920]
As discussed, this will no longer be offered to applicants.

However, we should not remove the field from the database, for our records.

**Comment by klappradla** [comment]
Why not also remove the field and all logic connected with it? If we're not using it, I don't see a point in having it around... 🤔

**Comment by ramonh** [comment]
I thought of this too @klappradla but I think we might want to keep it around, say, if we want to display stats from previous years. Wdyt?

**Comment by klappradla** [comment]
Valid point. But won't the contents of the DB and the current state of the application be exported by the end of the season anyways..?

If not, I'd suggest to approach it sorta like we did it when deprecating other application attributes last year: rename the column, prefix it with `deprecated_<original-name>` so that we know we can throw it out at some point.

However I'd still get rid of the logic inside the app related to this attribute - cause this looks like unused code to me then 🚜

**Comment by ramonh** [comment]
That sounds good to me! Sorry I was unclear, I intend to remove the volunteer logic as well 👍 

So I'll rename the column to `deprecated_<name>`

**Comment by F3PiX** [comment]
(Heads up: we use the `rgsoc-2018` label for issues that the student team can work on during Summer. Instead, I created a new Milestone for issues that need to be done before the Application Phase starts.)

**Comment by ramonh** [comment]
Oh cool, thanks for putting up with this github newbie 😅
