### ISSUE TITLE
On the community page, filter for the city should be there.

### ISSUE THREAD

**Issue by ArushiSinghal** [rails-girls-summer-of-code/rgsoc-teams#935]
As the teams have to choose coaches from the same city. So the filter for the city on the community page can help in finding the coaches from the same city.

**Comment by cesswairimu** [comment]
I would like to work on this.

**Comment by ArushiSinghal** [comment]
Hello, @cesswairimu I think admins have not given their idea's on this Issue. I am waiting for their approval. And then one of us can work on this issue.

**Comment by klappradla** [comment]
Hey @ArushiSinghal & @cesswairimu 👋 

Sorry it took me so long to get back to you 🙈 

This was indeed a feature which was originally planned for the community page. At least filtering by `country` was already worked on in [this PR](https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/849) by our lovely students from last year.

There is also [an existing open issue](https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/594) on this topic. I'll therefore close this one, so that we don't end up with the same information in various places.

If you'd like to work on implementing the filter for `location`, maybe quickly read over the existing communication in https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/594 first and ping me there if you need any more information or things are still unclear.
But we're of course happy about a PR for this 🎉
