### ISSUE TITLE
RSS Icon Misleading Link 

### ISSUE THREAD

**Issue by AnkitaKhurana** [rails-girls-summer-of-code/rgsoc-teams#944]
The RSS Icon in Activity Area is directing to a misleading link which needs to be corrected.

![image](https://user-images.githubusercontent.com/13145896/36641780-a2747cee-1a5b-11e8-86e2-f5f2845e18a1.png)
Rss Icon on the right most section

![image](https://user-images.githubusercontent.com/13145896/36641756-4655db74-1a5b-11e8-921b-faf7ca30e481.png)
URL it is directing to

**Comment by AnkitaKhurana** [comment]
I would like to work on this issue if it seems important.

**Comment by klappradla** [comment]
Hi @AnkitaKhurana 👋 

I'm sorry, but I fear I don't really understand the issue here 🙈 

What is the problem with the URL in your opinion? The link exposes the activities as an RSS feed in the [atom](https://en.wikipedia.org/wiki/Atom_(Web_standard)) xml format for feeds. I would not know how this should be done any different - afaik it's the default process as e.g. news sites use it as well.

Depending on your browser, Firefox for instance, you can directly subscribe to the feed from this url:
<img width="1792" alt="screen shot 2018-02-25 at 17 56 23" src="https://user-images.githubusercontent.com/3491815/36644071-386a2dfe-1a55-11e8-9484-56841bf4c1bc.png">

Therefore I'd close this here. Feel free to reopen in case I got you totally wrong and am overseeing an actual problem of the app 🙈
