### ISSUE TITLE
Remove "Time now" column from community page users' listing

### ISSUE THREAD

**Issue by AnkitaKhurana** [rails-girls-summer-of-code/rgsoc-teams#945]
The ‘Time Now’ column of a few community members is not fetching any results in the Community page.

![image](https://user-images.githubusercontent.com/13145896/36641820-1ec087c0-1a5c-11e8-9a61-f8f715e81eb2.png)

**Comment by AnkitaKhurana** [comment]
I would like to work on this issue.

**Comment by klappradla** [comment]
Hey @AnkitaKhurana ✌️ 

Thanx for reporting 🙏 

The question here is: how could this be "fixed"? The column is based on the `timezone` attribute of a user record which is right now non-mandatory. See the user form for this 👇 
![artboard 1](https://user-images.githubusercontent.com/3491815/36644195-00d78146-1a57-11e8-9c41-cc4a17e02c3d.png)

I'm personally strongly against making more attributes of the user profile *mandatory* unless they **really** have a benefit in making the program easier to run / easier for the orga team or something similar. Otherwise, it just raises the bar for new users creating their accounts, e.g. potential coaches, which would be sad if we'd miss them.

Right now, the `country` is a mandatory attribute. Guessing a user's timezone based on her country won't work though. Plus: eventually people want to change their timezone when they're travelling.. 🤔 

I would be inclined to close this issue as something we cannot "fix" (or maybe don't need to fix 😉 ). Or what would be your take on this? Did you already have an idea in mind how to solve this?

**Comment by klappradla** [comment]
**Edit:**
We just came up with an even better "fix™" for this issue @AnkitaKhurana 💡 

Let's just fully get rid of the `Time now` timezone column on the community table. It's not a super relevant information in this content and the table is already way to huge anyways.

Would you be interested in implementing this change?

**Comment by carpodaster** [comment]
I agree that removing the column is the way to go, seeing how few people seem to fill out that info (and that's ok, it's not required). We can, however, add an HTML title attribute hover to the location cell that holds the user's current local time (if their timezone is set)

**Comment by ramonh** [comment]
Hey @AnkitaKhurana, thanks again for reporting this issue! 

Are you still interested in handling this?

**Comment by agpiermarini** [comment]
Hi @ramonh, @carpodaster and @klappradla. From the above conversation, it appears that this is still an open item. I am a new contributor and think that this would be a great first issue. Would you like me to try to take care of it over the next day or two?

**Comment by klappradla** [comment]
Closed via #1027
