### ISSUE TITLE
Add feature to mention users in the comment and notify them.

### ISSUE THREAD

**Issue by SnehaMidha** [rails-girls-summer-of-code/rgsoc-teams#957]

**Comment by klappradla** [comment]
Hi @SnehaMidha 👋 

it would be handy if you could give a bit more context on the issue you are reporting, such as:
- which type of comments are you referring to?
- what would be the purpose / use case for mentioning users?
- how should they be notified?
- "how" should mentioning work in practice?

This being said, I fear that the feature is not *pressing™* enough for anyone of us to work on, since we have huge backlog of functionally more important things to fix and improve 🙈 

In order to implement `@` mentions like you have e.g. here on Github, we'd have to augment the simple HTML text-areas with loads of JS, eventually even move them over to some sort of rich text editor like `draft.js` or use libraries like `at.js`.
All of ☝️ is  a lot of effort and unlikely to happen until we have closed large amounts of our existing issues 🐌 

I'll therefore close this issue for now. Feel free to reopen it or file a new one, once this becomes relevant again. I hope you understand: being a small team, we have to keep the number of open issues to a number we're still able to overlook and keep in the back of our head. So we unfortunately cannot keep feature requests pointing to somewhere that far in the future 😞
