### ISSUE TITLE
show people's names in the application review

### ISSUE THREAD

**Issue by metakermit** [rails-girls-summer-of-code/rgsoc-teams#970]
Hi 👋 

just going through the applications (a bit late, sorry 😬 ) and thought that it would be handy if names and GitHub usernames of team members were also shown on the [applications page](https://teams.railsgirlssummerofcode.org/mentors/applications) and the application details page. Some of the people have already gotten in touch with us on GitHub and we know their names/usernames, but it's a bit hard to keep track of who's from what team, when all the team names are a bit abstract.

Cheers!

**Comment by ramonh** [comment]
Hey @metakermit Sorry I didn't get around to this sooner.

So the reason we weren't showing this before is because the mentor review stage of application reviews was during the blind phase.

Now that we've done away with that, however, it makes complete sense to show these again, so thank you very much for the feedback!

I think this would also be a great issue for students to use to start familiarising themselves with the teams app, so I'll label it thusly.

**Comment by metakermit** [comment]
Awesome, thanks Ramón and have a great weekend :)

**Comment by ramonh** [comment]
Same to you, thanks Dražen!

**Comment by klappradla** [comment]
Should be via #1031 and ready for you to use next year @metakermit 👋

**Comment by metakermit** [comment]
Nice, thanks a lot 🙌
